import { describe, expect, it, vi } from 'vitest';
import { ProductionAdmissionCoordinator, type ProductionAdmissionDependencies } from './production-admission.js';
const principal = { principalRef: 'principal://p', tenantId: 't', maximumScopes: ['run'], subject: 'p', issuer: 'idp', authenticatedAt: '2026-08-16T00:00:00.000Z', expiresAt: '2026-08-17T00:00:00.000Z' };
const request = { principal, requestedTenantId: 't', releaseRef: 'release://r', artifactDigests: [`sha256:${'a'.repeat(64)}`], grantRef: 'grant://g', targetRef: 'target://t', accountRef: 'account://a', invocationId: 'i', specDraft: { taskId: 'task', runId: 'run', attemptId: 'attempt' } } as never;
const reservation = { schemaVersion: '1', reservationRef: 'usage-reservation://1', tenantId: 't', accountRef: 'account://a', invocationId: 'i', ownerRef: 'principal://p', taskId: 'task', runId: 'run', attemptId: 'attempt', specRef: 'pending', upperBound: { admission: 1 }, state: 'RESERVED', fenceEpoch: 1, leaseExpiresAt: '2026-08-17T00:00:00.000Z', createdAt: '2026-08-16T00:00:00.000Z' } as const;
const base = (overrides: Partial<ProductionAdmissionDependencies> = {}): ProductionAdmissionDependencies => ({ readiness: { evaluate: async () => ({ decision: 'GO' as const, reasonCodes: [] }) }, supplyChain: { verifyExact: async () => true }, policy: { authorizeAdmission: async () => true }, acl: { allowed: async () => true }, dependencies: { healthy: async () => true }, ledger: { reserve: async () => reservation, release: vi.fn(async () => 'released') }, compensation: { recordOrphan: vi.fn(async () => undefined) }, audit: { append: vi.fn(async () => ({ auditRef: 'audit://1' })), query: async () => ({ records: [] }), health: async () => ({ healthy: true, checkedAt: new Date().toISOString() }) }, authority: { commit: vi.fn(async () => { throw new Error('commit failed'); }) }, ...overrides });
describe('production Admission coordinator', () => {
  it('makes zero authority calls on NO-GO', async () => { const dependencies = base({ readiness: { evaluate: async () => ({ decision: 'NO_GO' as const, reasonCodes: ['READINESS_RECORD_MISSING'] }) } }); await expect(new ProductionAdmissionCoordinator(dependencies, () => new Date('2026-08-16')).admit(request)).rejects.toThrow('NO_GO'); expect(dependencies.authority.commit).not.toHaveBeenCalled(); });
  it('releases a known reservation after post-reserve failure', async () => { const dependencies = base(); await expect(new ProductionAdmissionCoordinator(dependencies, () => new Date('2026-08-16')).admit(request)).rejects.toThrow('commit failed'); expect(dependencies.ledger.release).toHaveBeenCalledOnce(); expect(dependencies.compensation.recordOrphan).not.toHaveBeenCalled(); });
  it('durably records an orphan when compensation cannot prove release', async () => { const dependencies = base({ ledger: { reserve: async () => reservation, release: vi.fn(async () => 'conflict') } }); await expect(new ProductionAdmissionCoordinator(dependencies, () => new Date('2026-08-16')).admit(request)).rejects.toThrow('commit failed'); expect(dependencies.compensation.recordOrphan).toHaveBeenCalledOnce(); });
  it('does not commit when mandatory audit is unavailable', async () => { const dependencies = base({ audit: { append: async () => { throw new Error('audit down'); }, query: async () => ({ records: [] }), health: async () => ({ healthy: false, checkedAt: new Date().toISOString() }) } }); await expect(new ProductionAdmissionCoordinator(dependencies, () => new Date('2026-08-16')).admit(request)).rejects.toThrow('audit down'); expect(dependencies.authority.commit).not.toHaveBeenCalled(); expect(dependencies.ledger.release).toHaveBeenCalled(); });
});
