import { sha256Digest, type AgentExecutionEnvelope, type AgentTaskSpec, type UsageReservationV1 } from '@sage/agent-contracts';
import type { SecurityAuditPort, TrustedPrincipal } from '@sage/platform-ports';
export interface ProductionAdmissionRequest { readonly principal: TrustedPrincipal; readonly requestedTenantId: string; readonly releaseRef: string; readonly artifactDigests: readonly string[]; readonly grantRef: string; readonly approvalRef?: string; readonly targetRef: string; readonly accountRef: string; readonly invocationId: string; readonly specDraft: Omit<AgentTaskSpec, 'principalRef' | 'tenantId' | 'specRef' | 'specDigest'> }
export interface ProductionAdmissionDependencies { readonly readiness: { evaluate(): Promise<{ readonly decision: 'GO' | 'NO_GO'; readonly reasonCodes: readonly string[] }> }; readonly supplyChain: { verifyExact(input: { readonly tenantId: string; readonly releaseRef: string; readonly artifactDigests: readonly string[] }): Promise<boolean> }; readonly policy: { authorizeAdmission(input: ProductionAdmissionRequest): Promise<boolean> }; readonly acl: { allowed(input: { readonly tenantId: string; readonly principalRef: string; readonly refs: readonly string[] }): Promise<boolean> }; readonly dependencies: { healthy(): Promise<boolean> }; readonly ledger: { reserve(input: { readonly tenantId: string; readonly accountRef: string; readonly invocationId: string; readonly ownerRef: string; readonly taskId: string; readonly runId: string; readonly attemptId: string; readonly specRef: string; readonly upperBound: Readonly<Record<string, number>>; readonly leaseExpiresAt: string }): Promise<UsageReservationV1>; release(input: { readonly reservation: UsageReservationV1; readonly reason: string }): Promise<string> }; readonly compensation: { recordOrphan(input: { readonly reservation: UsageReservationV1; readonly reason: string; readonly causeCode: string; readonly recordedAt: string }): Promise<void> }; readonly audit: SecurityAuditPort; readonly authority: { commit(input: { readonly request: ProductionAdmissionRequest; readonly reservation: UsageReservationV1 }): Promise<{ readonly spec: AgentTaskSpec; readonly envelope: AgentExecutionEnvelope }> } }
export class ProductionAdmissionCoordinator {
  constructor(private readonly dependencies: ProductionAdmissionDependencies, private readonly now: () => Date = () => new Date()) {}
  async admit(request: ProductionAdmissionRequest) {
    const at = this.now().toISOString(); const audit = async (decision: string, reasonCode: string, digestValue: unknown) => this.dependencies.audit.append({ tenantId: request.requestedTenantId, occurredAt: at, category: 'supply_chain', decision, reasonCode, actorRef: request.principal.principalRef, correlation: { release_ref: request.releaseRef, invocation_ref: request.invocationId }, authorityDigest: sha256Digest(digestValue) });
    if (request.principal.tenantId !== request.requestedTenantId || Date.parse(request.principal.expiresAt) <= this.now().getTime()) { await audit('DENY', 'IDENTITY_TENANT_MISMATCH', request.principal); throw new Error('IDENTITY_TENANT_MISMATCH'); }
    if (request.artifactDigests.length === 0 || new Set(request.artifactDigests).size !== request.artifactDigests.length || !request.artifactDigests.every(value => /^sha256:[a-f0-9]{64}$/.test(value))) { await audit('DENY', 'SUPPLY_CHAIN_ARTIFACTS_MISSING', request.artifactDigests); throw new Error('SUPPLY_CHAIN_ARTIFACTS_MISSING'); }
    const readiness = await this.dependencies.readiness.evaluate(); if (readiness.decision !== 'GO') { await audit('DENY', 'NO_GO', readiness.reasonCodes); throw Object.assign(new Error('NO_GO'), { reasons: readiness.reasonCodes }); }
    const [supply, policy, acl, healthy] = await Promise.all([this.dependencies.supplyChain.verifyExact({ tenantId: request.requestedTenantId, releaseRef: request.releaseRef, artifactDigests: request.artifactDigests }), this.dependencies.policy.authorizeAdmission(request), this.dependencies.acl.allowed({ tenantId: request.requestedTenantId, principalRef: request.principal.principalRef, refs: [request.releaseRef, request.grantRef, ...(request.approvalRef ? [request.approvalRef] : []), request.targetRef] }), this.dependencies.dependencies.healthy()]);
    if (!supply) throw new Error('SUPPLY_CHAIN_UNVERIFIABLE'); if (!policy) throw new Error('GRANT_DENIED'); if (!acl) throw new Error('SCOPE_DENIED'); if (!healthy) throw new Error('DEPENDENCY_UNAVAILABLE');
    let reservation: UsageReservationV1 | undefined;
    try { reservation = await this.dependencies.ledger.reserve({ tenantId: request.requestedTenantId, accountRef: request.accountRef, invocationId: request.invocationId, ownerRef: request.principal.principalRef, taskId: request.specDraft.taskId, runId: request.specDraft.runId, attemptId: request.specDraft.attemptId, specRef: `pending-spec://${request.invocationId}`, upperBound: { admission: 1 }, leaseExpiresAt: new Date(this.now().getTime() + 60_000).toISOString() }); await audit('ALLOW', 'AUTHORIZED', { releaseRef: request.releaseRef, invocationId: request.invocationId, artifactDigests: request.artifactDigests }); return await this.dependencies.authority.commit({ request, reservation }); }
    catch (cause) { if (reservation) { let released = false; try { released = (await this.dependencies.ledger.release({ reservation, reason: 'admission_post_reserve_failure' })) === 'released' || (await this.dependencies.ledger.release({ reservation, reason: 'admission_post_reserve_failure_retry' })) === 'existing'; } catch { released = false; } if (!released) await this.dependencies.compensation.recordOrphan({ reservation, reason: 'admission_post_reserve_failure', causeCode: cause instanceof Error ? cause.message : 'ADMISSION_FAILURE', recordedAt: at }); } await audit('DENY', cause instanceof Error ? cause.message : 'ADMISSION_FAILURE', request.invocationId); throw cause; }
  }
}
