import type { AdapterHealth, SecurityAuditPort } from '@sage/platform-ports';
import { sha256Digest } from '@sage/agent-contracts';
export interface RegistrySupplyChainArtifact { readonly artifactKind: 'release' | 'engine_adapter' | 'model_adapter' | 'capability_provider'; readonly artifactRef: string; readonly artifactDigest: string; readonly attestationDigest: string; readonly validUntil: string }
export interface RegistrySupplyChainVerifier { verify(input: RegistrySupplyChainArtifact): Promise<{ readonly valid: boolean; readonly revoked: boolean; readonly observedDigest: string; readonly policyVersion: string }> }
export class ProductionRegistrySupplyChainGate { constructor(private readonly verifier?: RegistrySupplyChainVerifier, private readonly now: () => Date = () => new Date()) {} async assertPublishable(artifacts: readonly RegistrySupplyChainArtifact[]): Promise<void> { if (!this.verifier) throw new Error('SUPPLY_CHAIN_UNVERIFIABLE'); if (artifacts.length === 0 || new Set(artifacts.map(item => `${item.artifactKind}:${item.artifactRef}`)).size !== artifacts.length) throw new Error('SUPPLY_CHAIN_ARTIFACTS_MISSING'); for (const artifact of artifacts) { if (!/^sha256:[a-f0-9]{64}$/.test(artifact.artifactDigest) || !/^sha256:[a-f0-9]{64}$/.test(artifact.attestationDigest) || Date.parse(artifact.validUntil) <= this.now().getTime()) throw new Error('SUPPLY_CHAIN_ATTESTATION_STALE'); let result; try { result = await this.verifier.verify(artifact); } catch { throw new Error('SUPPLY_CHAIN_UNVERIFIABLE'); } if (!result.valid || result.revoked || result.observedDigest !== artifact.artifactDigest) throw new Error(result.revoked ? 'SUPPLY_CHAIN_REVOKED' : 'SUPPLY_CHAIN_POLICY_DENIED'); } } }
export const REQUIRED_REGISTRY_ADAPTERS = ['supply_chain', 'policy', 'revocation', 'registry_store', 'audit'] as const;
export class ProductionRegistryRuntime {
  private constructor(private readonly gate: ProductionRegistrySupplyChainGate, private readonly audit: SecurityAuditPort) {}
  static async create(input: { readonly gate: ProductionRegistrySupplyChainGate; readonly audit: SecurityAuditPort; readonly adapters: readonly { readonly name: typeof REQUIRED_REGISTRY_ADAPTERS[number]; health(): Promise<AdapterHealth> }[] }): Promise<ProductionRegistryRuntime> { const names = input.adapters.map(item => item.name); if (names.length !== REQUIRED_REGISTRY_ADAPTERS.length || new Set(names).size !== names.length || !REQUIRED_REGISTRY_ADAPTERS.every(name => names.includes(name))) throw new Error('PRODUCTION_ADAPTER_SET_INCOMPLETE'); const health = await Promise.allSettled(input.adapters.map(item => item.health())); if (health.some(item => item.status === 'rejected' || !item.value.healthy)) throw new Error('PRODUCTION_DEPENDENCY_UNAVAILABLE'); return new ProductionRegistryRuntime(input.gate, input.audit); }
  async publish<T>(input: { readonly tenantId: string; readonly actorRef: string; readonly releaseRef: string; readonly artifacts: readonly RegistrySupplyChainArtifact[]; readonly mutate: (auditFenceRef: string) => Promise<T>; readonly now?: () => Date }): Promise<T> { const occurredAt = (input.now ?? (() => new Date()))().toISOString(); try { await this.gate.assertPublishable(input.artifacts); } catch (cause) { await this.audit.append({ tenantId: input.tenantId, occurredAt, category: 'supply_chain', decision: 'DENY', reasonCode: cause instanceof Error ? cause.message : 'SUPPLY_CHAIN_UNVERIFIABLE', actorRef: input.actorRef, correlation: { release_ref: input.releaseRef }, authorityDigest: sha256Digest(input.artifacts) }); throw cause; } const authorityDigest = sha256Digest(input.artifacts); const pending = await this.audit.append({ tenantId: input.tenantId, occurredAt, category: 'supply_chain', decision: 'PENDING', reasonCode: 'REGISTRY_PUBLICATION_FENCED', actorRef: input.actorRef, correlation: { release_ref: input.releaseRef }, authorityDigest }); const result = await input.mutate(pending.auditRef); await this.audit.append({ tenantId: input.tenantId, occurredAt, category: 'supply_chain', decision: 'PUBLISHED', reasonCode: 'SUPPLY_CHAIN_VERIFIED', actorRef: input.actorRef, correlation: { release_ref: input.releaseRef, audit_fence_ref: pending.auditRef }, authorityDigest }); return result; }
}
