import {randomUUID} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {bundleWorkflowCode,NativeConnection,Worker} from '@temporalio/worker';
import {Pool} from 'pg';
import {renderToStaticMarkup} from 'react-dom/server';
import {afterAll,beforeAll,beforeEach,describe,expect,it} from 'vitest';
import type {HarnessCapabilities,HarnessPort,HarnessTurnRequest,HarnessTurnResult} from '@sage/agent-contracts';
import {LocalAgentClient} from '@sage/agent-client';
import {createAgentTaskActivities} from '@sage/agent-worker';
import {ChatPromotionAuthorizer,createChatApi,registerTaskRoutes} from '@sage/agent-api';
import {TaskDetail,type TaskViewModel} from '@sage/agent-web/tasks';
import {ChatStore} from '@sage/chat-domain';
import type {P6Correlation,P6MetricName,P6TelemetryRecorder} from '@sage/observability';
import {p6CorrelationComplete} from '@sage/observability';
import type {CredentialProvider} from '@sage/platform-ports';
import {TASK_TYPE,type TaskProjectionEvent,type TaskReconciliationStore,type TaskWorkflowState,type TaskArtifactReference} from '@sage/task-domain';
import {PostgresTaskStore} from '@sage/task-store-postgres';
import {LocalAesGcmSecretBackend} from '@sage/secret-vault';
import {randomBytes} from 'node:crypto';
import {createDevRegistryBundle,publishDevRegistry} from '@sage/temporal-registry';
import {DefaultTemporalClientConnector,TaskProjectionReconciler,TemporalClientFactory,TemporalTaskHistorySource,TrustedMultiTargetTaskController,TrustedTemporalRouter} from '@sage/temporal-routing';

const databaseUrl=process.env.P6_POSTGRES_URL;const temporalAddress=process.env.SAGE_TEMPORAL_ADDRESS;const integration=describe.skipIf(!databaseUrl);const tenantId='tenant-p6';
const workflowsPath=fileURLToPath(new URL('../../../packages/temporal-workflows/src/workflows.ts',import.meta.url));
class E2EHarness implements HarnessPort{readonly capabilities:HarnessCapabilities={harness:'p6-real-e2e',version:'1',supported:['events','checkpoint']};readonly effects:string[]=[];async executeTurn(request:HarnessTurnRequest):Promise<HarnessTurnResult>{this.effects.push(request.input);return {output:`durable:${request.input}`,done:true,toolCalls:0,tokens:1,checkpointRef:`checkpoint://p6/${request.runId}`};}}
class CaptureTelemetry implements P6TelemetryRecorder{readonly records:{name:P6MetricName;value:number;correlation:P6Correlation;fields:Readonly<Record<string,unknown>>}[]=[];record(name:P6MetricName,value:number,correlation:P6Correlation,fields:Readonly<Record<string,unknown>>={}){this.records.push({name,value,correlation:structuredClone(correlation),fields:structuredClone(fields)});}}
const credentials:CredentialProvider={async resolveCredential(request){return {value:new Uint8Array(),expiresAt:'2099-01-01T00:00:00.000Z',scope:request.scope};},async health(){return {healthy:true,checkedAt:new Date().toISOString()};}};
let chat:ChatStore;let tasks:PostgresTaskStore;let admin:Pool;let native:NativeConnection;let bundle:Awaited<ReturnType<typeof bundleWorkflowCode>>;
const secretBackend=new LocalAesGcmSecretBackend([randomBytes(32)]);
async function seedProvider(){const sealed=secretBackend.seal('p6-e2e-provider-key');await tasks.createProviderConnection(tenantId,'conn-p6-e2e',{name:'p6 provider',source:'user',adapterKind:'anthropic',baseUrl:'https://api.minimaxi.com/anthropic',modelId:'MiniMax-M3',enabled:true,updatedBy:'principal://p6',credential:{ciphertext:sealed.ciphertext,keyVersion:sealed.keyVersion,updatedAt:'2026-08-25T00:00:00.000Z'}},'2026-08-25T00:00:00.000Z');await tasks.upsertRunAgentSettings({tenantId,providerConnectionId:'conn-p6-e2e',updatedAt:'2026-08-25T00:00:00.000Z',updatedBy:'principal://p6'});}
const principal={authenticationId:'auth-p6-user',principalId:'user-p6',tenantId,roles:['chat-task-promoter','task-operator']};
const auth={tenantId,authenticator:{authenticate:(id:string)=>id===principal.authenticationId?principal:undefined},authorizer:{authorize:()=>true}} as const;
function registry(address:string){const value=createDevRegistryBundle('registry-p6-real');value.targets=value.targets.map((target)=>({...target,endpoint:target.targetId==='sage-dev-us'?address:target.endpoint,allowedTenantIds:[...target.allowedTenantIds,tenantId]}));return publishDevRegistry(value);}
function controller(factory:TemporalClientFactory,telemetry:CaptureTelemetry){return new TrustedMultiTargetTaskController({router:new TrustedTemporalRouter({registry:registry(temporalAddress!)}),clientFactory:factory,routingStore:tasks,projectionStore:tasks,tenantId,actorId:'authenticated-agent-api',contextId:'p6-authenticated-request',environment:'development',region:'us-east',residency:'us',projectionFreshnessThresholdMs:1000,telemetry});}
async function worker(harness:E2EHarness,telemetry:CaptureTelemetry,buildId:string,afterCommit?:()=>void|Promise<void>){return Worker.create({connection:native,namespace:'sage-dev',taskQueue:'sage-agent-task-us-v1',workflowBundle:bundle,activities:createAgentTaskActivities({liveClientFactory:()=>new LocalAgentClient({harness}),settingsStore:tasks,providerConnections:tasks,secretBackend,store:tasks,inputResolver:{async resolve(){return 'produce durable report';}},telemetry,...(afterCommit?{afterCommit}: {})}),buildId});}
beforeAll(async()=>{if(!databaseUrl)return;if(!temporalAddress)throw new Error('SAGE_TEMPORAL_ADDRESS_REQUIRED');bundle=await bundleWorkflowCode({workflowsPath});native=await NativeConnection.connect({address:temporalAddress});chat=new ChatStore({connectionString:databaseUrl});tasks=new PostgresTaskStore({connectionString:databaseUrl});admin=new Pool({connectionString:databaseUrl});await chat.migrate();await tasks.migrate();},60_000);
beforeEach(async()=>{await admin.query('TRUNCATE chat_promotion_audit,chat_task_associations,chat_timeline_events,chat_summaries,chat_runs,chat_message_parts,chat_messages,chat_sessions,task_projection_repair_audit,task_artifact_reference,task_event_projection,task_routing_rejection,task_routing,task_projection_outbox,task_projection,task_effect_ledger RESTART IDENTITY CASCADE');tasks.setProjectionWritesEnabled(true);});
afterAll(async()=>{if(!databaseUrl)return;if(chat)await chat.close();if(tasks)await tasks.close();if(admin)await admin.end();if(native)await native.close();});

integration.sequential('P6 real Temporal cross-layer acceptance',()=>{
  it('promotes persisted Chat through trusted routing to a real Worker, survives SSE interruption/Worker restart/store delay, reconciles real History, and preserves Artifact references',async()=>{
    const telemetry=new CaptureTelemetry();const harness=new E2EHarness();await seedProvider();const factory=new TemporalClientFactory({credentials,connector:new DefaultTemporalClientConnector(),tenantId});const subject=controller(factory,telemetry);
    let artifactDown=true;const firstWorkerRef:{value?:Worker}={};let stopAfterCommit=true;let committedResolve!:()=>void;const committed=new Promise<void>((resolve)=>{committedResolve=resolve;});
    const firstWorker=await worker(harness,telemetry,'sage-p6-worker-before-restart',()=>{if(stopAfterCommit){stopAfterCommit=false;committedResolve();firstWorkerRef.value!.shutdown();throw new Error('INJECTED_P6_WORKER_RESTART_AFTER_COMMIT');}});firstWorkerRef.value=firstWorker;const running1=firstWorker.run();
    const app=await createChatApi({store:chat,tenantId,providerConnections:tasks,secretBackend,liveClientFactory:()=>new LocalAgentClient({harness}),promotion:{controller:subject,authenticator:{authenticate:(id:string|undefined)=>id===principal.authenticationId?principal:undefined},authorizer:new ChatPromotionAuthorizer(),telemetry}});
    registerTaskRoutes(app,subject,{...auth,queryStore:tasks,freshnessThresholdMs:1000,telemetry,artifactResolver:{async resolve(reference:TaskArtifactReference){if(artifactDown)throw new Error('temporary artifact outage');return reference;}}});
    await app.listen({host:'127.0.0.1',port:0});const address=app.server.address();if(!address||typeof address==='string')throw new Error('P6_API_ADDRESS_UNAVAILABLE');const base=`http://127.0.0.1:${address.port}`;
    try{
      const session=(await app.inject({method:'POST',url:'/v1/chat/sessions',payload:{title:'P6 long request'}})).json<{sessionId:string}>();
      const accepted=(await app.inject({method:'POST',url:`/v1/chat/sessions/${session.sessionId}/messages`,payload:{parts:[{kind:'text',text:'Produce a durable long-running report with an artifact'}],provider:{connectionId:'conn-p6-e2e'}}})).json<{message:{messageId:string};run:{runId:string}}>();
      const cursor=(await chat.listTimeline(tenantId,session.sessionId)).at(-1)?.sequence??0;const abort=new AbortController();const stream=await fetch(`${base}/v1/chat/sessions/${session.sessionId}/timeline?afterSequence=${cursor}`,{signal:abort.signal});expect(stream.ok).toBe(true);const reader=stream.body!.getReader();
      tasks.setProjectionWritesEnabled(false);
      const promoted=await app.inject({method:'POST',url:`/v1/chat/messages/${accepted.message.messageId}/promotions`,headers:{'x-authentication-id':principal.authenticationId},payload:{mode:'explicit',taskType:TASK_TYPE}});expect(promoted.statusCode,promoted.body).toBe(202);
      const chunk=await Promise.race([reader.read(),new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error('SSE_RECOVERY_TIMEOUT')),5000))]);expect(new TextDecoder().decode(chunk.value)).toContain('promotion_pending');abort.abort();await reader.cancel().catch(()=>undefined);
      const association=await chat.getPromotion(tenantId,accepted.message.messageId);expect(association).toMatchObject({status:'routed',sessionId:session.sessionId,runId:accepted.run.runId,principalId:'user-p6'});const routing=await tasks.getTaskRouting(tenantId,association!.taskId);expect(routing).toMatchObject({status:'started',snapshot:{targetId:'sage-dev-us',taskQueue:'sage-agent-task-us-v1'},startEnvelope:{input:{sessionId:session.sessionId,runId:accepted.run.runId,messageId:accepted.message.messageId}}});
      await committed;await running1;const second=await worker(harness,telemetry,'sage-p6-worker-after-restart');const final=await second.runUntil(factory.forSnapshot(routing!.snapshot).then((client)=>client.getHandle(routing!.workflowId).result() as Promise<TaskWorkflowState>));expect(final).toMatchObject({status:'succeeded',artifactRef:expect.stringMatching(/^artifact:\/\//)});expect(harness.effects.filter((value)=>value==='produce durable report')).toHaveLength(1);
      const reconciler=new TaskProjectionReconciler({tenantId,store:tasks as TaskReconciliationStore,clientFactory:factory,historySource:new TemporalTaskHistorySource(),batchSize:10,freshnessThresholdMs:0,telemetry});
      expect(await reconciler.runBatch()).toMatchObject({inspected:1,repaired:0,failed:1});expect((await tasks.listRepairAudits(tenantId,association!.taskId)).at(-1)).toMatchObject({failureCode:'PROJECTION_WRITE_FAILED',retryable:true});
      tasks.setProjectionWritesEnabled(true);expect(await reconciler.runBatch()).toMatchObject({inspected:1,repaired:1,failed:0});const repaired=await tasks.getProjection(tenantId,association!.taskId);expect(repaired).toMatchObject({status:'succeeded',projectionSource:'history'});expect(Number(repaired!.historyEventId)).toBeGreaterThan(0);
      const recovered=(await fetch(`${base}/v1/chat/sessions/${session.sessionId}/events?afterSequence=${cursor}`,{credentials:'include'}).then((response)=>response.json())) as {events:{payload:{kind:string;status?:string}}[]};expect(recovered.events.flatMap((event)=>event.payload.kind==='task'?[event.payload.status]:[])).toEqual(['promotion_pending','routed']);
      const headers={'x-authentication-id':principal.authenticationId};const detail=(await app.inject({method:'GET',url:`/v1/tasks/${association!.taskId}`,headers})).json<TaskViewModel>();expect(detail).toMatchObject({status:'succeeded',targetSnapshot:{targetId:'sage-dev-us'},freshness:'fresh',sessionId:session.sessionId,runId:accepted.run.runId});const timeline=(await app.inject({method:'GET',url:`/v1/tasks/${association!.taskId}/events`,headers})).json<{events:TaskProjectionEvent[]}>();expect(timeline.events).toEqual(expect.arrayContaining([expect.objectContaining({type:'agent.task.succeeded'})]));
      const artifact=(await tasks.listTaskArtifacts(tenantId,association!.taskId))[0]!;expect(artifact.artifactRef).toMatch(/^artifact:\/\//);const unavailable=await app.inject({method:'GET',url:`/v1/tasks/${association!.taskId}/artifacts/${artifact.artifactId}`,headers});expect(unavailable.statusCode).toBe(503);expect(unavailable.json()).toMatchObject({artifact:{artifactRef:artifact.artifactRef}});artifactDown=false;expect((await app.inject({method:'GET',url:`/v1/tasks/${association!.taskId}/artifacts/${artifact.artifactId}`,headers})).statusCode).toBe(200);expect(renderToStaticMarkup(<TaskDetail task={detail} events={timeline.events} artifacts={[artifact]}/>)).toContain(artifact.artifactRef);
      const names=new Set(telemetry.records.map((record)=>record.name));for(const name of ['sage_chat_task_promotions_total','sage_task_route_decisions_total','sage_task_worker_attempt_total','sage_task_projection_lag_ms','sage_task_reconcile_retryable_failure_total','sage_artifact_store_unavailable_total'] as const)expect(names.has(name),name).toBe(true);for(const record of telemetry.records){expect(record.correlation).toMatchObject({tenant_id:tenantId,message_id:accepted.message.messageId,session_id:session.sessionId,run_id:accepted.run.runId});expect(p6CorrelationComplete(record.correlation),record.name).toBe(true);}expect(JSON.stringify(telemetry.records)).not.toContain('secret://');
    }finally{tasks.setProjectionWritesEnabled(true);await app.close();await factory.close();}
  },60_000);

  it('binds an unreachable selected target with no fallback and emits target-unavailable correlation',async()=>{
    const telemetry=new CaptureTelemetry();const badBundle=createDevRegistryBundle('registry-p6-unreachable');badBundle.targets=badBundle.targets.map((target)=>({...target,endpoint:target.targetId==='sage-dev-us'?'127.0.0.1:1':target.endpoint,allowedTenantIds:[...target.allowedTenantIds,tenantId]}));const factory=new TemporalClientFactory({credentials,connector:new DefaultTemporalClientConnector(),tenantId});const subject=new TrustedMultiTargetTaskController({router:new TrustedTemporalRouter({registry:publishDevRegistry(badBundle)}),clientFactory:factory,routingStore:tasks,projectionStore:tasks,tenantId,actorId:'authenticated-agent-api',contextId:'p6-target-outage',environment:'development',region:'us-east',residency:'us',telemetry});const taskId=`cluster-down-${randomUUID()}`;const correlation={sessionId:'session-target-down',runId:'run-target-down',messageId:'message-target-down'};
    await expect(subject.create({taskId,taskType:TASK_TYPE,inputRef:`task-input://p6/${taskId}`},undefined,correlation)).rejects.toMatchObject({code:'WORKFLOW_START_OUTCOME_UNKNOWN',targetId:'sage-dev-us'});const record=await tasks.getTaskRouting(tenantId,taskId);expect(record).toMatchObject({status:'start_pending',snapshot:{targetId:'sage-dev-us',endpoint:'127.0.0.1:1'},startEnvelope:{input:correlation}});expect(record!.decision.chosenTargetId).toBe('sage-dev-us');expect(telemetry.records).toEqual(expect.arrayContaining([expect.objectContaining({name:'sage_temporal_target_unavailable_total',correlation:expect.objectContaining({tenant_id:tenantId,message_id:correlation.messageId,session_id:correlation.sessionId,run_id:correlation.runId,task_id:taskId,target_id:'sage-dev-us'})})]));expect(telemetry.records.every((item)=>p6CorrelationComplete(item.correlation))).toBe(true);await factory.close();
  },20_000);
});
