import { describe, expect, it } from 'vitest';
import { DefaultDenyEgressPolicy, RevalidatingEgressConnector, productionSandboxProfile, assertProductionSandboxProfile } from '@sage/tool-runtime';
import { CircuitBreaker, RetryBudget, WeightedFairQueue, advanceCanary } from '@sage/production-governance';
const digest = `sha256:${'a'.repeat(64)}`;
describe('Phase 4 fault/rollback matrix (local engineering only)', () => {
  it.each([['private', '10.0.0.1'], ['metadata', '169.254.169.254'], ['loopback', '127.0.0.1'], ['ipv6-link-local', 'fe80::1']])('blocks %s egress', async (_name, ip) => { const policy = new DefaultDenyEgressPolicy([{ scheme: 'https', hostname: 'api.example', ports: [443], pathPrefixes: ['/'] }], { resolve: async () => [ip] }); await expect(policy.authorize('https://api.example/')).rejects.toThrow('EGRESS_ADDRESS_DENIED'); });
  it('fails closed when DNS, connection revalidation, sandbox profile, or provider health is unavailable', async () => {
    const down = new DefaultDenyEgressPolicy([{ scheme: 'https', hostname: 'api.example', ports: [443], pathPrefixes: ['/'] }], { resolve: async () => { throw new Error('dns down'); } }); await expect(down.authorize('https://api.example/')).rejects.toThrow('dns down');
    const policy = new DefaultDenyEgressPolicy([{ scheme: 'https', hostname: 'api.example', ports: [443], pathPrefixes: ['/'] }], { resolve: async () => ['8.8.8.8'] }); const bypass = new RevalidatingEgressConnector(policy, { request: async () => ({ status: 200, headers: {}, body: new Uint8Array() }), health: async () => ({ healthy: true, checkedAt: new Date().toISOString() }) }); await expect(bypass.request({ url: 'https://api.example/', signal: new AbortController().signal })).rejects.toThrow('EGRESS_CONNECTION_NOT_REVALIDATED');
    const profile = productionSandboxProfile({ network: 'none', timeoutMs: 100, outputBytes: 100 }); expect(() => assertProductionSandboxProfile({ ...profile, capabilities: ['SYS_ADMIN'] })).toThrow('SANDBOX_CAPABILITY_INVALID');
    let clock = 0; const breaker = new CircuitBreaker(2, 100, () => clock); breaker.failure(); breaker.failure(); expect(breaker.allow()).toBe(false); clock = 101; expect(breaker.allow()).toBe(true);
  });
  it('blocks unknown Effect retries and canary advancement without evaluated current GO/evidence objects', () => {
    expect(new RetryBudget(100).consume({ effectState: 'EFFECT_UNKNOWN' })).toBe(false); const state = { completed: [], stopped: false, productionEvidenceRefs: [] } as const;
    expect(advanceCanary(state, { stage: 'identity_secret' })).toMatchObject({ stopped: true, completed: [] });
    expect(advanceCanary(state, { stage: 'identity_secret', now: '2026-08-16T00:00:00.000Z', readiness: { decision: 'GO', recordRef: 'readiness://1', recordDigest: digest, validUntil: '2026-08-17T00:00:00.000Z' }, evidence: [{ evidenceRef: 'evidence://identity', evidenceDigest: digest, environmentRef: 'production', outcome: 'PASS', productionEquivalent: true, evaluatedAt: '2026-08-15T00:00:00.000Z', validUntil: '2026-08-17T00:00:00.000Z' }] })).toMatchObject({ stopped: false, completed: ['identity_secret'] });
  });
  it('fails queue overload closed without starving a quiet tenant', () => { const queue = new WeightedFairQueue([{ tenantId: 'noisy', weight: 1, concurrency: 1, queueLimit: 1 }, { tenantId: 'quiet', weight: 1, concurrency: 1, queueLimit: 1 }], 2); queue.enqueue('noisy', 1); expect(() => queue.enqueue('noisy', 2)).toThrow('TENANT_BACKPRESSURE'); queue.enqueue('quiet', 3); const selected = [queue.take()!, queue.take()!]; expect(new Set(selected.map(item => item.tenantId))).toEqual(new Set(['noisy', 'quiet'])); selected.forEach(item => item.release()); });
  it('models rollback as stopping new work while preserving committed authorities', () => { const authority = Object.freeze({ effect: 'COMMITTED', usage: 'COMMITTED', checkpoint: 'SEALED', artifact: 'COMMITTED', spec: 'IMMUTABLE', history: 'IMMUTABLE' }); const rollback = { admissionOpen: false, drain: true, cancelNew: true, authority }; expect(rollback.admissionOpen).toBe(false); expect(rollback.authority).toBe(authority); expect(Object.isFrozen(rollback.authority)).toBe(true); });
});
