import type {
  AuthorizationReceipt, CapabilityApproval, CapabilityGrant, DependencyHealth, EffectClaim, EffectReceipt, EffectResolution,
  KillSwitch, ProductionReadinessRecord, UsageReceiptV1, UsageReservationV1
} from '@sage/agent-contracts';
import type { AdapterHealth } from './index.js';

export interface TrustedPrincipal { readonly principalRef: string; readonly tenantId: string; readonly maximumScopes: readonly string[]; readonly subject: string; readonly issuer: string; readonly authenticatedAt: string; readonly expiresAt: string }
export interface IdentityVerificationPort { verify(input: { readonly bearerToken: string; readonly expectedAudience: string; readonly expectedNonce?: string; readonly now: string }): Promise<TrustedPrincipal>; health(): Promise<AdapterHealth> }
export interface ReplayGuardPort { claim(input: { readonly issuer: string; readonly tokenId: string; readonly expiresAt: string }): Promise<'claimed' | 'replayed'> }
export interface WorkloadIdentityExchangePort { exchange(input: { readonly workloadRef: string; readonly tenantId: string; readonly environment: string; readonly audience: string; readonly scopes: readonly string[]; readonly maximumTtlSeconds: number }): Promise<{ readonly accessToken: Uint8Array; readonly expiresAt: string; readonly audience: string; readonly bindingDigest: string }>; health(): Promise<AdapterHealth> }

export interface SecretLease { readonly secretRef: string; readonly version: string; readonly value: Uint8Array; readonly expiresAt: string; destroy(): void }
export interface SecretManagerPort { lease(input: { readonly secretRef: string; readonly tenantId: string; readonly environment: string; readonly purpose: string; readonly minimumVersion?: string; readonly maximumTtlSeconds: number }): Promise<SecretLease>; health(): Promise<AdapterHealth> }
export interface KmsPort { encrypt(input: { readonly keyRef: string; readonly tenantId: string; readonly plaintext: Uint8Array; readonly context: Readonly<Record<string, string>> }): Promise<{ readonly ciphertext: Uint8Array; readonly keyVersion: string }>; decrypt(input: { readonly keyRef: string; readonly tenantId: string; readonly ciphertext: Uint8Array; readonly context: Readonly<Record<string, string>> }): Promise<{ readonly plaintext: Uint8Array; readonly keyVersion: string }>; health(): Promise<AdapterHealth> }
export interface ObjectStorePort { putTemporary(input: { readonly tenantId: string; readonly operationId: string; readonly ciphertext: Uint8Array; readonly digest: string }): Promise<{ readonly temporaryRef: string; readonly etag: string }>; promote(input: { readonly tenantId: string; readonly temporaryRef: string; readonly committedRef: string; readonly expectedDigest: string; readonly fenceEpoch: number }): Promise<{ readonly status: 'promoted' | 'existing'; readonly etag: string }>; get(input: { readonly tenantId: string; readonly committedRef: string }): Promise<Uint8Array | undefined>; delete(input: { readonly tenantId: string; readonly objectRef: string }): Promise<void>; health(): Promise<AdapterHealth> }

export interface GovernanceSnapshotPort { getGrant(input: { readonly tenantId: string; readonly grantRef: string }): Promise<CapabilityGrant | undefined>; getApproval(input: { readonly tenantId: string; readonly approvalRef: string }): Promise<CapabilityApproval | undefined>; listKills(input: { readonly tenantId: string; readonly scopeRefs: readonly string[] }): Promise<readonly KillSwitch[]>; revocationRevision(input: { readonly tenantId: string; readonly toolRef: string; readonly providerRef: string }): Promise<{ readonly denied: boolean; readonly revision: number; readonly validUntil: string }>; health(): Promise<AdapterHealth> }
export interface ProductionAuthorizationPort { authorize(input: { readonly tenantId: string; readonly principalRef: string; readonly specRef: string; readonly grantRef: string; readonly approvalRef?: string; readonly releaseRef?: string; readonly modelRouteRef?: string; readonly toolRef: string; readonly toolVersion: string; readonly providerRef: string; readonly providerBuildDigest: string; readonly canonicalInputDigest: string; readonly semanticActionId: string; readonly access: 'read' | 'write'; readonly risk: 'low' | 'medium' | 'high'; readonly resourceScopes: readonly string[]; readonly environment: string; readonly requestedCount: number; readonly requestedCost: number; readonly ledgerRevision: number; readonly ledgerAvailable: boolean; readonly now: string }): Promise<AuthorizationReceipt> }

export type EffectClaimResult = { readonly status: 'claimed'; readonly fenceEpoch: number; readonly leaseExpiresAt: string } | { readonly status: 'replay'; readonly receipt: EffectReceipt } | { readonly status: 'in_progress' } | { readonly status: 'conflict'; readonly code: 'EFFECT_CONFLICT' } | { readonly status: 'unknown'; readonly receipt: EffectReceipt };
export interface ToolEffectLedgerPort { claim(claim: EffectClaim): Promise<EffectClaimResult>; commit(input: { readonly claim: EffectClaim; readonly fenceEpoch: number; readonly receipt: EffectReceipt }): Promise<{ readonly status: 'committed' | 'existing'; readonly receipt: EffectReceipt } | { readonly status: 'conflict'; readonly code: 'EFFECT_FENCE_LOST' | 'EFFECT_CONFLICT' }>; markUnknown(input: { readonly claim: EffectClaim; readonly fenceEpoch: number; readonly receipt: EffectReceipt }): Promise<EffectReceipt>; recordLateReceipt?(input: { readonly claim: EffectClaim; readonly fenceEpoch: number; readonly receipt: EffectReceipt; readonly evidenceDigest: string }): Promise<{ readonly status: 'committed' | 'existing' } | { readonly status: 'conflict'; readonly code: string }>; resolve(input: { readonly resolution: EffectResolution; readonly resolverScopes: readonly string[] }): Promise<{ readonly status: 'resolved' | 'existing'; readonly resolution: EffectResolution } | { readonly status: 'denied' | 'conflict'; readonly code: string }>; reconcile(input: { readonly tenantId: string; readonly now: string; readonly limit: number }): Promise<readonly EffectClaim[]>; health(): Promise<AdapterHealth> }
export interface ProductionConsumptionLedgerPort { reserve(input: Omit<UsageReservationV1, 'reservationRef' | 'state' | 'fenceEpoch' | 'createdAt'>): Promise<UsageReservationV1>; commit(input: { readonly reservation: UsageReservationV1; readonly receipt: UsageReceiptV1 }): Promise<{ readonly status: 'committed' | 'existing'; readonly receipt: UsageReceiptV1 } | { readonly status: 'conflict'; readonly code: 'USAGE_CONFLICT' | 'USAGE_FENCE_LOST' }>; release(input: { readonly reservation: UsageReservationV1; readonly reason: string }): Promise<'released' | 'existing' | 'conflict'>; recoverOrphan?(input: { readonly reservation: UsageReservationV1; readonly now: string; readonly evidenceDigest: string }): Promise<'expired' | 'existing' | 'conflict'>; getAuthoritativeBalance(input: { readonly tenantId: string; readonly accountRef: string }): Promise<{ readonly available: Readonly<Record<string, number>>; readonly reserved: Readonly<Record<string, number>>; readonly revision: number }>; reconcile(input: { readonly tenantId: string; readonly now: string; readonly limit: number }): Promise<readonly UsageReservationV1[]>; health(): Promise<AdapterHealth>;
  /**
   * Schedule 维度预算账户（P8 可选能力）：schedule 触发的 run 以 `schedule:<scheduleId>` 为 accountRef，
   * 账户初始 balance 即声明上限（余量模型），reserve 天然执行跨 run 聚合硬上限；结算窗口由
   * checkScheduleBudget 滚动（balance 重置为上限）；commit 结算同事务累加窗口 used（invocation 幂等）。
   * 不支持该能力的 adapter 保持 undefined，调度触发方必须 fail closed。
   */
  upsertScheduleAccount?(input: { readonly tenantId: string; readonly scheduleId: string; readonly limits: Readonly<Record<string, number>>; readonly windowMs?: number }): Promise<'stored' | 'existing'>;
  checkScheduleBudget?(input: { readonly tenantId: string; readonly scheduleId: string; readonly requested: Readonly<Record<string, number>>; readonly now: string }): Promise<{ readonly ok: boolean; readonly available: Readonly<Record<string, number>>; readonly windowStartMs: number; readonly usedInWindow: Readonly<Record<string, number>> }> }

export interface ArtifactCheckpointCommitPort { stage(input: { readonly tenantId: string; readonly operationId: string; readonly body: Uint8Array; readonly bodyDigest: string; readonly keyRef: string; readonly lineageRefs: readonly string[]; readonly retentionClass: string }): Promise<{ readonly state: 'pending' | 'committed'; readonly operationId: string; readonly committedRef?: string; readonly fenceEpoch: number }>; finalize(input: { readonly tenantId: string; readonly operationId: string; readonly fenceEpoch: number }): Promise<{ readonly state: 'committed' | 'quarantined'; readonly committedRef?: string; readonly reason?: string }>; resolve(input: { readonly tenantId: string; readonly committedRef: string; readonly expectedDigest: string }): Promise<Uint8Array | undefined>; reconcile(input: { readonly tenantId: string; readonly now: string; readonly limit: number }): Promise<readonly string[]>; health(): Promise<AdapterHealth> }

export interface SecurityAuditPort { append(input: { readonly tenantId: string; readonly occurredAt: string; readonly category: 'identity' | 'grant' | 'approval' | 'revocation' | 'effect' | 'usage' | 'resolution' | 'supply_chain' | 'reconcile' | 'kill'; readonly decision: string; readonly reasonCode: string; readonly actorRef: string; readonly correlation: Readonly<Record<string, string | number>>; readonly authorityDigest: string }): Promise<{ readonly auditRef: string }>; query(input: { readonly tenantId: string; readonly from: string; readonly to: string; readonly limit: number; readonly cursor?: string }): Promise<{ readonly records: readonly Readonly<Record<string, unknown>>[]; readonly nextCursor?: string }>; health(): Promise<AdapterHealth> }

export interface ProductionCheckpointDescriptor {
  readonly tenantId: string; readonly operationId: string; readonly taskId: string; readonly runId: string; readonly attemptId: string;
  readonly specDigest: string; readonly sequence: number; readonly stateSchema: string; readonly engineCodec: string; readonly runtimeContractMajor: number;
  readonly effectReceiptRefs: readonly string[]; readonly usageReceiptRefs: readonly string[]; readonly bodyDigest: string; readonly keyRef: string; readonly retentionClass: string;
}
export interface ProductionCheckpointLifecyclePort {
  stageCheckpoint(input: ProductionCheckpointDescriptor & { readonly body: Uint8Array }): Promise<{ readonly state: 'pending' | 'committed'; readonly operationId: string; readonly fenceEpoch: number; readonly checkpointRef?: string }>;
  finalizeCheckpoint(input: { readonly tenantId: string; readonly operationId: string; readonly fenceEpoch: number }): Promise<{ readonly state: 'committed' | 'quarantined'; readonly checkpointRef?: string; readonly reason?: string }>;
  resumeCheckpoint(input: Omit<ProductionCheckpointDescriptor, 'operationId' | 'bodyDigest' | 'keyRef' | 'retentionClass'> & { readonly checkpointRef: string; readonly expectedBodyDigest: string; readonly now: string }): Promise<Uint8Array | undefined>;
  reconcileCheckpoint(input: { readonly tenantId: string; readonly now: string; readonly limit: number }): Promise<readonly string[]>;
  setCheckpointLegalHold(input: { readonly tenantId: string; readonly checkpointRef: string; readonly active: boolean; readonly actorRef: string }): Promise<void>;
  rotateCheckpointKey(input: { readonly tenantId: string; readonly checkpointRef: string; readonly currentKeyRef: string; readonly nextKeyRef: string }): Promise<void>;
  tombstoneCheckpoint(input: { readonly tenantId: string; readonly checkpointRef: string; readonly now: string; readonly backupExpiresAt: string }): Promise<'tombstoned' | 'held' | 'conflict'>;
  expireCheckpointBackup(input: { readonly tenantId: string; readonly checkpointRef: string; readonly now: string }): Promise<'deleted' | 'pending' | 'held'>;
  health(): Promise<AdapterHealth>;
}

export interface ProductionReadinessRecordProvider { load(environmentRef: string): Promise<ProductionReadinessRecord | unknown | undefined>; health(): Promise<AdapterHealth> }
export interface ProductionReadinessVerifier { verify(record: ProductionReadinessRecord): Promise<{ readonly valid: boolean; readonly recordDigest?: string; readonly verifiedHumanSubjects: readonly { readonly role: string; readonly subjectRef: string }[]; readonly reason?: string }> }
export interface DependencyHealthPort { check(): Promise<readonly DependencyHealth[]> }
