import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Locale = 'zh-CN' | 'en';
export const LOCALE_STORAGE_KEY = 'sage.web.locale';

const enMessages = {
  brandSubtitle: 'Beyond thought, action at its best', brandName: 'Sage', workspace: 'Workspace', configuration: 'Configuration', chat: 'Chat', tasks: 'Tasks', providers: 'Providers', packages: 'Packages', new: 'new', localWorkspace: 'Local workspace', systemRuntime: 'System runtime', localPiHarness: 'Local Pi Harness', localDevelopmentMode: 'Local development mode', runtimeFootnote: 'Sage v0.1 · Local development mode', mainNavigation: 'Main navigation', notifications: 'Notifications', accountMenu: 'Open account menu', home: 'Sage home', collapseSidebar: 'Collapse sidebar', expandSidebar: 'Expand sidebar',
  workspaceUnavailable: 'Workspace unavailable', cannotOpenView: 'We could not open this view', runtimeFailed: 'Web runtime failed to start', returnToHistory: 'Return to history',
  conversationHistory: 'Conversation history', chatWorkspace: 'Chat workspace', resumeConversation: 'Resume a retained conversation or explicitly start a new one.', newChat: '+ New Chat', creating: 'Creating…', chatHistoryUnavailable: 'Chat history unavailable', searchSessionTitles: 'Search session titles', searchTitles: 'Search titles', status: 'Status', all: 'All', open: 'Open', closed: 'Closed', refresh: 'Refresh', loadingRetainedSessions: 'Loading retained sessions', noRetainedSessions: 'No retained sessions', startChatExplicit: 'Starting a Chat is always an explicit action.', untitledChat: 'Untitled Chat', noPersistedMessages: 'No persisted messages yet', loadMore: 'Load more', loading: 'Loading…', chatSessionHistory: 'Chat session history', historyViewLabel: 'History view', conversationsTab: 'Conversations', archiveTab: 'Archive', archivedSessionHistory: 'Archived chat session history', archiveAction: 'Archive', unarchiveAction: 'Restore', deleteAction: 'Delete', deleteConfirmWarning: 'Permanently delete this conversation? This cannot be undone.', confirmDelete: 'Delete forever', noArchivedSessions: 'No archived conversations', archiveEmptyHint: 'Archived conversations appear here. Restore them, or delete them permanently.', archiveFailed: 'Could not archive the conversation', unarchiveFailed: 'Could not restore the conversation', deleteSessionFailed: 'Could not delete the conversation', conversationArchived: 'Conversation archived.', conversationRestored: 'Conversation restored.', conversationDeleted: 'Conversation permanently deleted.', archivedReadOnly: 'Conversation archived · Read only', archivedReadOnlyExplanation: 'This conversation is archived and cannot accept messages or retries. Restore it from the archive view to continue.',
  liveConversation: 'Live conversation', liveStreamConnected: 'Live stream connected', connecting: 'Connecting…', streamReconnecting: 'Stream reconnecting', localPiRuntime: 'Local Pi runtime', session: 'SESSION', events: 'EVENTS', run: 'RUN', ready: 'ready', openTaskWorkspace: 'Open task workspace', somethingNeedsAttention: 'Something needs attention', dismissError: 'Dismiss error', dismissNotice: 'Dismiss notice', recoveringConversation: 'Recovering conversation', loadingEvents: 'Loading persisted events and reconnecting the live stream…', closedReadOnly: 'Closed session · Read only', closedExplanation: 'This retained conversation cannot accept messages or retries and will not be reopened automatically.', composerReadOnly: 'Conversation unavailable · Read only', composerReadOnlyExplanation: 'The session could not be recovered and is currently read-only.', tryAsking: 'Try asking', summarizeProject: 'Summarize project', createTask: 'Create a Task', exploreRisk: 'Explore a risk', message: 'Message', askAnything: 'Ask Sage anything…', enterToSend: 'Enter to send · Shift + Enter for a new line', sending: 'Sending…', send: 'Send', thinking: 'Thinking…', thoughtProcess: 'Thought process', userMessage: 'User message', assistantMessage: 'Assistant message', eventStream: 'Event stream', copyEventStream: 'Copy event stream', backToConversations: 'Back to conversations', runtime: 'RUNTIME', chatRuntime: 'Chat runtime', runtimeUnavailable: 'The selected provider profile is no longer complete. Re-select it on the Providers page.', runtimeKeyMissing: 'The selected provider has no API key in this tab. Enter it on the Providers page and retry.',  eventStreamCopied: 'Copied {count} events as JSONL for troubleshooting.', copyFailedMessage: 'Copying the event stream failed. Clipboard is unavailable and the fallback copy did not succeed.', workspaceRuntimeUnavailable: 'The selected workspace provider is no longer available. Re-select it on the Providers page.',
  chatUnavailable: 'This Chat is no longer available', chatRetention: 'The session may have passed retention. No replacement session was created.', startOutcome: 'Start with a clear outcome', chatPrompt: 'Ask Sage to explore an idea, summarize a document, or turn a conversation into a durable Task.', promoteTask: 'Promote to Task', retryRun: 'Retry run', taskUpdate: 'Task update', toolActivity: 'Tool activity', artifact: 'Artifact', runState: 'Run state', error: 'Error', messageEvent: 'Message', needsAttention: 'Needs attention', tool: 'Tool', taskCardTitle: 'Task Card · Make this conversation durable', taskCardBody: 'Promote a persisted user message to create a Task with pause, retry, and cancellation controls.', viewTasks: 'View Tasks', durableExecution: 'Durable execution', task: 'Task', mostRecentFirst: 'Most recent first', noTasks: 'No Tasks yet', promoteImportant: 'Promote an important Chat message and it will appear here with durable controls.', goToChat: 'Go to Chat', taskDetail: 'Task detail', allTasks: 'All tasks', revision: 'Revision', execution: 'Execution', workflow: 'Workflow', target: 'Target', namespace: 'Namespace', taskQueue: 'Task queue', attempt: 'Attempt', controls: 'Controls', controlsAuthorized: 'Controls are authorized by the local workspace session.', taskControls: 'Task controls', executionHistory: 'Execution history', timeline: 'Timeline', eventsCount: '{count} events', noProjectionEvents: 'No projection events have been recorded yet.', outputs: 'Outputs', artifacts: 'Artifacts', artifactsPending: 'Artifacts will appear here when a slice commits an output.', runningCount: '{count} running', operationsCenter: 'Operations center', tasksSubtitle: 'Observe durable work, inspect its immutable target, and control execution safely.', taskDataUnavailable: 'Task data unavailable', refreshingTask: 'Refreshing task detail…', searchTasks: 'Search tasks', searchTaskPlaceholder: 'Search by task, type, or target', allStatuses: 'All statuses', loadingTaskProjections: 'Loading task projections', readingDurableState: 'Reading the latest durable state…', unavailable: 'Not available', projection: 'Projection',
  workspaceSettings: 'Workspace settings', providersSubtitle: 'Provider profiles are browser-local metadata and never change the executing runtime.', addProvider: '+ Add provider', readOnlyExecution: 'Read-only execution assembly', inUse: 'In use', catalogAvailable: 'Catalog available', catalogStale: 'Catalog stale · using last-known-good', catalogUnavailable: 'Catalog unavailable', checked: 'checked {value}', syncCatalog: 'Sync catalog', syncing: 'Syncing…', externalProfiles: 'External profiles', configured: '{count} configured', providerUnassigned: 'Provider unassigned', modelUnassigned: 'Model unassigned', checkConnection: 'Check connection for {name}', check: 'Check', checking: 'Checking…', connected: 'Connected', unauthorized: 'Unauthorized', profileUnavailable: 'Unavailable', noExternalProfiles: 'No external profiles. Add one explicitly.', runtimeBoundary: 'Runtime boundary', profilesNeverEnter: 'Profiles stay browser-local. Selecting one in Chat sends an ephemeral route for that run only; Tasks never receive provider data.', selectOrAdd: 'Select or add an external profile', localPiOnly: 'Local Pi remains the only system runtime in use.', newProfile: 'New profile', editProfile: 'Edit profile', untitledProvider: 'Untitled provider', provider: 'Provider', providerSearch: 'Provider search', searchProviders: 'Search providers', noProviders: 'No providers found', displayName: 'Display name', providerNamePlaceholder: 'Provider name', model: 'Model', modelSearch: 'Model search', selectModel: 'Select a model', noModels: 'No models found', adapterKind: 'Adapter kind', unassignedMetadata: 'Unassigned metadata', openAiCompatible: 'OpenAI-compatible', anthropic: 'Anthropic', baseUrl: 'Base URL', baseUrlPlaceholder: 'Source did not publish a URL; enter HTTPS manually if needed', sourceNote: 'Source: {source} · never guessed from npm or provider identity.', apiKey: 'API key (current tab only)', configuredThisTab: 'Configured in this tab · enter replacement', notConfiguredThisTab: 'Not configured in this tab', availableMetadata: 'Show in profile list', doesNotMean: 'Only the Chat runtime picker can use a profile for a run.', profileReady: 'Ready', profileOff: 'Off', profileIncomplete: 'Incomplete', cancel: 'Cancel', saveProfile: 'Save profile', saving: 'Saving…', pauseControl: 'Pause', resumeControl: 'Resume', cancelControl: 'Cancel', retryControl: 'Retry', taskTimeline: 'Task timeline', taskArtifacts: 'Task artifacts', statusRunning: 'Running', statusPaused: 'Paused', statusFailed: 'Failed', statusSucceeded: 'Succeeded', statusCancelled: 'Cancelled', statusEffectUnknown: 'Effect unknown', statusFresh: 'Fresh', statusStale: 'Stale', statusUnavailable: 'Unavailable',
runAgent: 'Run agent', runAgentSubtitle: 'Default provider for ai-app package runs. Credentials stay in the trusted server environment and are never stored here. Chat-page external profiles are not affected.', defaultProviderLabel: 'Default provider', providerOptionEcho: 'Offline — deterministic local harness; never calls a model', offlineModeActive: 'Package runs: offline mode (no model calls); chat external profiles are unaffected', noUsableWorkspaceProvider: 'Package runs: no usable workspace provider — add and select one below, or stay in offline mode; chat external profiles are unaffected', runAgentSaved: 'Run agent settings saved.', runAgentSaveFailed: 'Could not save run agent settings', runAgentUnavailable: 'Run agent settings unavailable', providerOptionConnection: '{name} — workspace provider (sealed server-side)', connectionReady: 'Package runs: workspace provider "{name}" ready', connectionUnavailable: 'Package runs: workspace provider "{name}" unavailable (missing, disabled, or no credential)', workspaceProviders: 'Workspace providers', workspaceProvidersSubtitle: 'Trusted server-side provider entries. Credentials are sealed server-side (write-only) and never touch the browser. Usable by package runs and, once selected, by chat.', addWorkspaceProvider: '+ Add workspace provider', editWorkspaceProvider: 'Edit workspace provider {name}', deleteWorkspaceProvider: 'Delete workspace provider {name}', noWorkspaceProviders: 'No workspace providers yet. Add one so package runs can use a preset provider instead of process env keys.', workspaceProviderSaved: 'Workspace provider saved.', workspaceProviderDeleted: 'Workspace provider deleted.', workspaceProviderSaveFailed: 'Could not save the workspace provider', workspaceProviderDeleteFailed: 'Could not delete the workspace provider', workspaceProviderRequired: 'Name, public HTTPS base URL, model, and an API key (on create) are required.', workspaceProvidersUnavailable: 'Workspace providers unavailable', apiKeyServer: 'API key (sealed server-side, write-only)', apiKeyRequiredPlaceholder: 'Paste the provider API key; it is sealed and never readable again', apiKeyRotatePlaceholder: 'Enter a new key to rotate the stored credential', sourceUser: 'user', sourceDeploymentEnv: 'deployment env', credentialPresent: 'Credential stored', credentialMissing: 'No credential', saveWorkspaceProvider: 'Save workspace provider',
  language: 'Language', chinese: '中文', english: 'English', languageSwitcher: 'Language',
  retryRequested: 'Retry requested. Watching the live timeline.', promotionAccepted: 'Task promotion accepted. The live timeline will show routing progress.', connectionFailed: 'Connection check failed', providerConnected: 'Provider connected.', providerUnavailable: 'Provider connection unavailable.', selectModelBeforeCheck: 'Select a model and Base URL before checking the connection.', enterApiKeyBeforeCheck: 'Enter an API key in this tab before checking the connection.', nameProviderModelRequired: 'Name, provider, and model metadata are required.', validHttpsRequired: 'Enabled URL adapters require a valid HTTPS Base URL.', catalogUpdatedProviders: 'Catalog updated. Provider options were reloaded.', catalogUpdatedModels: 'Catalog updated. Model options were reloaded without changing the saved profile.', reloadCatalog: 'Catalog updated during selection. Reload options before choosing a model.', savedMetadata: '{name} saved as browser-local metadata.', catalogSyncStatus: 'Catalog sync {status}', catalogSyncAttempt: ' · {attempt}', taskControlFailed: 'Task control failed', taskRequestFailed: 'Task request failed', taskDetailFailed: 'Task detail failed', messageFailed: 'Message failed', retryFailed: 'Retry failed', promotionFailed: 'Promotion failed', recoveryFailed: 'Chat recovery failed', sessionHistoryUnavailable: 'Session history unavailable', createSessionFailed: 'Could not create Chat session',
  packagesSubtitle: 'Browse registered ai apps, inspect manifests and assets, and start a run from an immutable Release.', noPackages: 'No packages yet', noPackagesHint: 'Register an ai app package via the API or script; it will appear here.', packageDataUnavailable: 'Package data unavailable', packageNotFound: 'Package not found', packageDetail: 'Package detail', allPackages: 'All packages', releases: 'Releases', latestVersion: 'Latest version', releaseCount: '{count} releases', updated: 'Updated', manifest: 'Manifest', assets: 'Assets', noAssets: 'No assets in this package', asset: 'Asset', releaseHistory: 'Release history', contentDigest: 'Content digest', lockDigest: 'Lock digest', compilerBuild: 'Compiler build', startRun: 'Start a run', startRunHint: 'Enter the user input for this package. The run will be created from the latest Release.', runInput: 'User input', runInputPlaceholder: 'Describe what you want the app to do…', runInputRequired: 'User input is required', startingRun: 'Starting run…', startRunAction: 'Start run', runStarted: 'Run started', viewRun: 'View run', runStartFailed: 'Could not start the run', assetPreview: 'Asset preview', manifestEntry: 'Entry prompt', modelRoute: 'Model route', skills: 'Skills', capabilities: 'Capabilities',
  newApp: '+ New App', createApp: 'Create App', creatingApp: 'Creating…', appId: 'App ID', appIdHint: 'Lowercase letters, digits, and hyphens; must start and end with a letter or digit.', appName: 'App name', appDescription: 'Description', appIdRequired: 'App ID is required', appNameRequired: 'App name is required', appIdInvalid: 'Invalid App ID format', appCreated: 'App created', createAppFailed: 'Could not create the App', uploadNewVersion: 'Upload new version', uploadVersion: 'Upload version', uploadingVersion: 'Uploading…', uploadHint: 'Upload the source package files (app.yaml, prompts/, references/) to register a new version.', uploadSucceeded: 'New version registered', uploadFailed: 'Could not upload the package', uploadFilesRequired: 'At least the app.yaml file is required', deleteApp: 'Delete App', deleteAppConfirm: 'Delete this App? It will be hidden from the list. Registered releases are kept for audit.', deleteAppConfirmAction: 'Delete App', deletingApp: 'Deleting…', appDeleted: 'App deleted', deleteAppFailed: 'Could not delete the App', cancelAction: 'Cancel', versionHistory: 'Version history', uploadFiles: 'Package files (one per line, path then content)', uploadFilesPlaceholder: 'Paste files as JSON: { "app.yaml": "...", "prompts/system.md": "..." }', uploadFilesInvalid: 'Files must be a JSON object of path → content',
} as const;

const zhMessages: { readonly [K in keyof typeof enMessages]: string } = {
  brandSubtitle: '不止于思，极致于行', brandName: '思极', workspace: '工作区', configuration: '配置', chat: '对话', tasks: '任务', providers: '服务商', packages: '应用', new: '新', localWorkspace: '本地工作区', systemRuntime: '系统运行时', localPiHarness: '本地 Pi Harness', localDevelopmentMode: '本地开发模式', runtimeFootnote: 'Sage v0.1 · 本地开发模式', mainNavigation: '主导航', notifications: '通知', accountMenu: '打开账户菜单', home: 'Sage 首页', collapseSidebar: '收起侧边栏', expandSidebar: '展开侧边栏', workspaceUnavailable: '工作区不可用', cannotOpenView: '无法打开此页面', runtimeFailed: 'Web 运行时启动失败', returnToHistory: '返回历史记录',
  conversationHistory: '对话历史', chatWorkspace: '对话工作区', resumeConversation: '继续保留的对话，或明确开始新的对话。', newChat: '+ 新建对话', creating: '创建中…', chatHistoryUnavailable: '对话历史不可用', searchSessionTitles: '搜索会话标题', searchTitles: '搜索标题', status: '状态', all: '全部', open: '开放', closed: '已关闭', refresh: '刷新', loadingRetainedSessions: '正在加载保留的会话', noRetainedSessions: '暂无保留的会话', startChatExplicit: '开始对话始终需要明确操作。', untitledChat: '未命名对话', noPersistedMessages: '尚无持久化消息', loadMore: '加载更多', loading: '加载中…', chatSessionHistory: '对话会话历史', historyViewLabel: '历史视图', conversationsTab: '对话', archiveTab: '归档', archivedSessionHistory: '已归档对话会话历史', archiveAction: '归档', unarchiveAction: '恢复', deleteAction: '删除', deleteConfirmWarning: '彻底删除该对话？此操作不可撤销。', confirmDelete: '彻底删除', noArchivedSessions: '暂无归档对话', archiveEmptyHint: '归档的对话会显示在这里，可恢复或彻底删除。', archiveFailed: '归档对话失败', unarchiveFailed: '恢复对话失败', deleteSessionFailed: '删除对话失败', conversationArchived: '对话已归档。', conversationRestored: '对话已恢复。', conversationDeleted: '对话已彻底删除。', archivedReadOnly: '对话已归档 · 只读', archivedReadOnlyExplanation: '此对话已归档，不能接收消息或重试。可在归档视图恢复后继续。',
  liveConversation: '实时对话', liveStreamConnected: '实时流已连接', connecting: '连接中…', streamReconnecting: '实时流重连中', localPiRuntime: '本地 Pi 运行时', session: '会话', events: '事件', run: '运行', ready: '就绪', openTaskWorkspace: '打开任务工作区', somethingNeedsAttention: '需要关注', dismissError: '关闭错误', dismissNotice: '关闭提示', recoveringConversation: '正在恢复对话', loadingEvents: '正在加载持久化事件并连接实时流…', closedReadOnly: '会话已关闭 · 只读', closedExplanation: '此保留对话不能接收消息或重试，也不会自动重新打开。', composerReadOnly: '对话不可用 · 只读', composerReadOnlyExplanation: '无法恢复会话，当前为只读状态。', tryAsking: '试着问问', summarizeProject: '总结项目', createTask: '创建任务', exploreRisk: '探索风险', message: '消息', askAnything: '想问 Sage 什么？', enterToSend: 'Enter 发送 · Shift + Enter 换行', sending: '发送中…', send: '发送', thinking: '思考中…', thoughtProcess: '思考过程', userMessage: '用户消息', assistantMessage: '助手消息', eventStream: '事件流', copyEventStream: '复制事件流', backToConversations: '返回对话列表', runtime: '运行时', chatRuntime: '对话运行时', runtimeUnavailable: '所选 provider 配置已不完整，请在 Providers 页重新配置。', runtimeKeyMissing: '所选 provider 在此标签页没有 API 密钥，请在 Providers 页输入后重试。',  eventStreamCopied: '已复制 {count} 个事件（JSONL），可用于排查。', copyFailedMessage: '复制事件流失败：剪贴板不可用且回退复制未成功。', workspaceRuntimeUnavailable: '所选工作区 provider 已不可用，请在 Providers 页重新选择。',
  chatUnavailable: '此对话已不可用', chatRetention: '会话可能已超过保留期限，未创建替代会话。', startOutcome: '从明确目标开始', chatPrompt: '让 Sage 探索想法、总结文档，或将对话转为持久任务。', promoteTask: '提升为任务', retryRun: '重试运行', taskUpdate: '任务更新', toolActivity: '工具活动', artifact: '产物', runState: '运行状态', error: '错误', messageEvent: '消息', needsAttention: '需要关注', tool: '工具', taskCardTitle: '任务卡片 · 让此对话持久化', taskCardBody: '提升一条已持久化的用户消息来创建任务，并获得暂停、重试和取消控制。', viewTasks: '查看任务', durableExecution: '持久执行', task: '任务', mostRecentFirst: '按最新时间排序', noTasks: '暂无任务', promoteImportant: '提升重要的对话消息后，它会出现在这里并提供持久控制。', goToChat: '前往对话', taskDetail: '任务详情', allTasks: '全部任务', revision: '修订版本', execution: '执行', workflow: '工作流', target: '目标', namespace: '命名空间', taskQueue: '任务队列', attempt: '尝试次数', controls: '控制', controlsAuthorized: '控制操作由本地工作区会话授权。', taskControls: '任务控制', executionHistory: '执行历史', timeline: '时间线', eventsCount: '{count} 个事件', noProjectionEvents: '尚未记录投影事件。', outputs: '输出', artifacts: '产物', artifactsPending: '切片提交输出后，产物会显示在这里。', runningCount: '{count} 个运行中', operationsCenter: '运维中心', tasksSubtitle: '观察持久工作，检查不可变目标，并安全控制执行。', taskDataUnavailable: '任务数据不可用', refreshingTask: '正在刷新任务详情…', searchTasks: '搜索任务', searchTaskPlaceholder: '按任务、类型或目标搜索', allStatuses: '所有状态', loadingTaskProjections: '正在加载任务投影', readingDurableState: '正在读取最新持久状态…', unavailable: '不可用', projection: '投影',
  workspaceSettings: '工作区设置', providersSubtitle: '服务商配置是浏览器本地元数据，不会改变执行中的运行时。', addProvider: '+ 添加服务商', readOnlyExecution: '只读执行组装', inUse: '使用中', catalogAvailable: '目录可用', catalogStale: '目录已过期 · 使用最近可用版本', catalogUnavailable: '目录不可用', checked: '检查于 {value}', syncCatalog: '同步目录', syncing: '同步中…', externalProfiles: '外部配置', configured: '已配置 {count} 个', providerUnassigned: '未分配服务商', modelUnassigned: '未分配模型', checkConnection: '检查 {name} 的连接', check: '检查', checking: '检查中…', connected: '已连接', unauthorized: '未授权', profileUnavailable: '不可用', noExternalProfiles: '暂无外部配置，请明确添加。', runtimeBoundary: '运行时边界', profilesNeverEnter: '配置仍是浏览器本地元数据；仅在对话页选择后随该次运行临时下发，任务请求不会携带任何服务商数据。', selectOrAdd: '选择或添加外部配置', localPiOnly: '本地 Pi 仍是唯一正在使用的系统运行时。', newProfile: '新建配置', editProfile: '编辑配置', untitledProvider: '未命名服务商', provider: '服务商', providerSearch: '搜索服务商', searchProviders: '搜索服务商', noProviders: '未找到服务商', displayName: '显示名称', providerNamePlaceholder: '服务商名称', model: '模型', modelSearch: '搜索模型', selectModel: '选择模型', noModels: '未找到模型', adapterKind: '适配器类型', unassignedMetadata: '未分配元数据', openAiCompatible: 'OpenAI 兼容', anthropic: 'Anthropic', baseUrl: '基础 URL', baseUrlPlaceholder: '来源未发布 URL；如有需要请输入 HTTPS 地址', sourceNote: '来源：{source} · 不会从 npm 或服务商身份推测。', apiKey: 'API 密钥（仅当前标签页）', configuredThisTab: '已在此标签页配置 · 输入新密钥替换', notConfiguredThisTab: '此标签页尚未配置', availableMetadata: '列入可选配置', doesNotMean: '仅对话运行时选择器可为单次运行启用配置。', profileReady: '可选', profileOff: '未启用', profileIncomplete: '未完成', cancel: '取消', saveProfile: '保存配置', saving: '保存中…', pauseControl: '暂停', resumeControl: '继续', cancelControl: '取消', retryControl: '重试', taskTimeline: '任务时间线', taskArtifacts: '任务产物', statusRunning: '运行中', statusPaused: '已暂停', statusFailed: '失败', statusSucceeded: '已成功', statusCancelled: '已取消', statusEffectUnknown: '效果未知', statusFresh: '新鲜', statusStale: '已过期', statusUnavailable: '不可用',
runAgent: '运行 Agent', runAgentSubtitle: 'ai-app 包运行的默认 provider。凭据只保存在受信服务端环境，绝不在此存储。对话页外部配置不受影响。', defaultProviderLabel: '默认 provider', providerOptionEcho: '离线模式 — 确定性本地 harness；不调用模型', offlineModeActive: '包运行：离线模式（不调用模型）；对话页外部配置不受影响', noUsableWorkspaceProvider: '包运行：无可用工作区 provider — 在下方添加并选择，或保持离线模式；对话页外部配置不受影响', runAgentSaved: '运行 Agent 设置已保存。', runAgentSaveFailed: '保存运行 Agent 设置失败', runAgentUnavailable: '运行 Agent 设置不可用', providerOptionConnection: '{name} — 工作区 provider（服务端密封）', connectionReady: '包运行：工作区 provider「{name}」就绪', connectionUnavailable: '包运行：工作区 provider「{name}」不可用（缺失、停用或无凭据）', workspaceProviders: '工作区 provider', workspaceProvidersSubtitle: '受信服务端 provider 条目。凭据在服务端密封存储（只写不读），绝不进入浏览器。包运行可用；对话页选择后亦可用。', addWorkspaceProvider: '+ 添加工作区 provider', editWorkspaceProvider: '编辑工作区 provider {name}', deleteWorkspaceProvider: '删除工作区 provider {name}', noWorkspaceProviders: '暂无工作区 provider。添加后包运行即可使用预设 provider，而不再依赖进程环境变量密钥。', workspaceProviderSaved: '工作区 provider 已保存。', workspaceProviderDeleted: '工作区 provider 已删除。', workspaceProviderSaveFailed: '保存工作区 provider 失败', workspaceProviderDeleteFailed: '删除工作区 provider 失败', workspaceProviderRequired: '名称、公共 HTTPS 基础 URL、模型为必填；新建时还需 API 密钥。', workspaceProvidersUnavailable: '工作区 provider 不可用', apiKeyServer: 'API 密钥（服务端密封，只写不读）', apiKeyRequiredPlaceholder: '粘贴 provider API 密钥；将被密封且此后不可读取', apiKeyRotatePlaceholder: '输入新密钥以轮换已托管凭据', sourceUser: '用户', sourceDeploymentEnv: '部署环境', credentialPresent: '凭据已托管', credentialMissing: '无凭据', saveWorkspaceProvider: '保存工作区 provider',
  language: '语言', chinese: '中文', english: 'English', languageSwitcher: '语言', retryRequested: '已请求重试，正在观察实时时间线。', promotionAccepted: '任务提升已接受，实时时间线将显示路由进度。', connectionFailed: '连接检查失败', providerConnected: '服务商已连接。', providerUnavailable: '服务商连接不可用。', selectModelBeforeCheck: '请先选择模型和基础 URL，再检查连接。', enterApiKeyBeforeCheck: '请在此标签页输入 API 密钥，再检查连接。', nameProviderModelRequired: '名称、服务商和模型元数据为必填项。', validHttpsRequired: '启用 URL 适配器需要有效的 HTTPS 基础 URL。', catalogUpdatedProviders: '目录已更新，已重新加载服务商选项。', catalogUpdatedModels: '目录已更新，已重新加载模型选项，保存的配置未改变。', reloadCatalog: '选择期间目录已更新，请重新加载选项后再选择模型。', savedMetadata: '{name} 已保存为浏览器本地元数据。', catalogSyncStatus: '目录同步 {status}', catalogSyncAttempt: ' · {attempt}', taskControlFailed: '任务控制失败', taskRequestFailed: '任务请求失败', taskDetailFailed: '任务详情加载失败', messageFailed: '消息发送失败', retryFailed: '重试失败', promotionFailed: '提升失败', recoveryFailed: '对话恢复失败', sessionHistoryUnavailable: '对话历史不可用', createSessionFailed: '无法创建对话会话',
  packagesSubtitle: '浏览已登记的 ai app 应用，检查 manifest 与资产，并从不可变 Release 发起运行。', noPackages: '暂无应用', noPackagesHint: '通过 API 或脚本登记 ai app 包后，它会显示在这里。', packageDataUnavailable: '应用数据不可用', packageNotFound: '应用不存在', packageDetail: '应用详情', allPackages: '全部应用', releases: 'Release', latestVersion: '最新版本', releaseCount: '{count} 个 Release', updated: '更新时间', manifest: '清单', assets: '资产', noAssets: '该应用没有资产', asset: '资产', releaseHistory: 'Release 历史', contentDigest: '内容摘要', lockDigest: '锁摘要', compilerBuild: '编译器构建', startRun: '发起运行', startRunHint: '输入该应用的用户输入。将基于最新 Release 创建运行。', runInput: '用户输入', runInputPlaceholder: '描述你希望应用做什么…', runInputRequired: '用户输入为必填项', startingRun: '正在发起运行…', startRunAction: '发起运行', runStarted: '运行已发起', viewRun: '查看运行', runStartFailed: '发起运行失败', assetPreview: '资产预览', manifestEntry: '入口提示词', modelRoute: '模型路由', skills: '技能', capabilities: '能力',
  newApp: '+ 新建应用', createApp: '新建应用', creatingApp: '创建中…', appId: '应用 ID', appIdHint: '小写字母、数字与连字符，须以字母或数字开头与结尾。', appName: '应用名称', appDescription: '描述', appIdRequired: '应用 ID 为必填项', appNameRequired: '应用名称为必填项', appIdInvalid: '应用 ID 格式不正确', appCreated: '应用已创建', createAppFailed: '创建应用失败', uploadNewVersion: '上传新版本', uploadVersion: '上传版本', uploadingVersion: '上传中…', uploadHint: '上传源包文件（app.yaml、prompts/、references/）登记为新版本。', uploadSucceeded: '新版本已登记', uploadFailed: '上传应用包失败', uploadFilesRequired: '至少需要 app.yaml 文件', deleteApp: '删除应用', deleteAppConfirm: '删除该应用？它将从列表隐藏，已登记的 Release 会保留用于审计。', deleteAppConfirmAction: '删除应用', deletingApp: '删除中…', appDeleted: '应用已删除', deleteAppFailed: '删除应用失败', cancelAction: '取消', versionHistory: '版本历史', uploadFiles: '应用包文件（JSON：路径 → 内容）', uploadFilesPlaceholder: '粘贴 JSON：{ "app.yaml": "...", "prompts/system.md": "..." }', uploadFilesInvalid: '文件必须是「路径 → 内容」的 JSON 对象',
};

export const messages = { en: enMessages, 'zh-CN': zhMessages } as const;
export type MessageKey = keyof typeof enMessages;
export type MessageValues = Readonly<Record<string, string | number>>;
export const messageKeys = Object.keys(enMessages) as MessageKey[];

export function normalizeLocale(value: unknown): Locale | undefined {
  if (typeof value !== 'string') return undefined;
  const normalized = value.trim().toLowerCase();
  if (/^zh(?:-|$)/.test(normalized)) return 'zh-CN';
  if (/^en(?:-|$)/.test(normalized)) return 'en';
  return undefined;
}

export interface LocaleNavigator { readonly languages?: readonly string[]; readonly language?: string }
export interface LocaleStorage { getItem(key: string): string | null; setItem(key: string, value: string): void }

export function resolveInitialLocale(storage?: LocaleStorage, navigatorLike?: LocaleNavigator): Locale {
  try { const persisted = normalizeLocale(storage?.getItem(LOCALE_STORAGE_KEY)); if (persisted) return persisted; } catch { /* isolated storage failure */ }
  try {
    const candidates = [...(navigatorLike?.languages ?? []), navigatorLike?.language].filter((value): value is string => typeof value === 'string' && value.length > 0);
    for (const candidate of candidates) { const detected = normalizeLocale(candidate); if (detected) return detected; }
  } catch { /* isolated language API failure */ }
  return 'zh-CN';
}

function browserStorage(): LocaleStorage | undefined { try { return typeof window === 'undefined' ? undefined : window.localStorage; } catch { return undefined; } }
function browserNavigator(): LocaleNavigator | undefined { try { return typeof navigator === 'undefined' ? undefined : navigator; } catch { return undefined; } }
function interpolate(template: string, values?: MessageValues): string { return values ? template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`)) : template; }

export interface LocaleContextValue { readonly locale: Locale; readonly setLocale: (locale: Locale) => void; readonly t: (key: MessageKey, values?: MessageValues) => string; readonly formatDateTime: (value: string | Date) => string; readonly formatTime: (value: string | Date) => string }
const fallback: LocaleContextValue = { locale: 'en', setLocale: () => undefined, t: (key, values) => interpolate(enMessages[key], values), formatDateTime: (value) => new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)), formatTime: (value) => new Intl.DateTimeFormat('en', { hour: '2-digit', minute: '2-digit' }).format(new Date(value)) };
const LocaleContext = createContext<LocaleContextValue>(fallback);

export function LocaleProvider({ children }: { readonly children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => resolveInitialLocale(browserStorage(), browserNavigator()));
  useEffect(() => { document.documentElement.lang = locale; }, [locale]);
  const setLocale = (next: Locale) => { setLocaleState(next); try { browserStorage()?.setItem(LOCALE_STORAGE_KEY, next); } catch { /* best effort persistence */ } };
  const value = useMemo<LocaleContextValue>(() => ({ locale, setLocale, t: (key, values) => interpolate(messages[locale][key], values), formatDateTime: (value) => new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)), formatTime: (value) => new Intl.DateTimeFormat(locale, { hour: '2-digit', minute: '2-digit' }).format(new Date(value)) }), [locale]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}
export function useLocale(): LocaleContextValue { return useContext(LocaleContext); }
