import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Locale = 'zh-CN' | 'en';
export const LOCALE_STORAGE_KEY = 'sage.web.locale';

const enMessages = {
  schedules: 'Schedules', scheduleDataUnavailable: 'Schedule data unavailable', scheduleAuthRequired: 'Service token missing or not accepted: configure SAGE_SERVICE_TOKEN / SAGE_SERVICE_TOKEN_HASHES on the server, then refresh.', loadingSchedules: 'Loading schedules…', noSchedules: 'No schedules yet', scheduleId: 'Schedule', scheduleTrigger: 'Trigger', scheduleBinding: 'Release binding', nextFire: 'Next fire', actions: 'Actions', pause: 'Pause', resume: 'Resume', delete: 'Delete', confirmScheduleDelete: 'Delete this schedule?', scheduleTriggerHistory: 'Trigger history', loadingTriggerHistory: 'Loading trigger history…', noTriggerEvents: 'No trigger events yet', brandName: 'Sage', workspace: 'Workspace', configuration: 'Configuration', chat: 'Chat', tasks: 'Tasks', providers: 'Providers', packages: 'Packages', new: 'new', localWorkspace: 'Local workspace', systemRuntime: 'System runtime', localDevelopmentMode: 'Local development mode', mainNavigation: 'Main navigation', accountMenu: 'Open account menu', home: 'Sage home', collapseSidebar: 'Collapse sidebar', expandSidebar: 'Expand sidebar',
  workspaceUnavailable: 'Workspace unavailable', cannotOpenView: 'We could not open this view', runtimeFailed: 'Web runtime failed to start', returnToHistory: 'Return to history',
  conversationHistory: 'Conversation history', newChat: '+ New Chat', creating: 'Creating…', chatHistoryUnavailable: 'Chat history unavailable', searchSessionTitles: 'Search session titles', searchTitles: 'Search titles', status: 'Status', all: 'All', open: 'Open', closed: 'Closed', refresh: 'Refresh', loadingRetainedSessions: 'Loading retained sessions', noRetainedSessions: 'No conversations yet', untitledChat: 'Untitled Chat', noPersistedMessages: 'No persisted messages yet', loadMore: 'Load more', loading: 'Loading…', chatSessionHistory: 'Chat session history', historyViewLabel: 'History view', conversationsTab: 'Conversations', archiveTab: 'Archive', archivedSessionHistory: 'Archived chat session history', archiveAction: 'Archive', unarchiveAction: 'Restore', deleteAction: 'Delete', deleteConfirmWarning: 'Permanently delete this conversation? This cannot be undone.', confirmDelete: 'Delete forever', noArchivedSessions: 'No archived conversations', archiveFailed: 'Could not archive the conversation', unarchiveFailed: 'Could not restore the conversation', deleteSessionFailed: 'Could not delete the conversation', conversationArchived: 'Archived.', conversationRestored: 'Restored.', conversationDeleted: 'Deleted.', archivedReadOnly: 'Conversation archived · Read only', liveStreamConnected: 'Live stream connected', connecting: 'Connecting…', streamReconnecting: 'Stream reconnecting', session: 'SESSION', events: 'EVENTS', run: 'RUN', ready: 'ready', openTaskWorkspace: 'Open task workspace', somethingNeedsAttention: 'Something needs attention', dismissError: 'Dismiss error', dismissNotice: 'Dismiss notice', recoveringConversation: 'Recovering conversation', loadingEvents: 'Loading events and reconnecting…', closedReadOnly: 'Closed session · Read only', composerReadOnly: 'Conversation unavailable · Read only', tryAsking: 'Try asking', summarizeProject: 'Summarize project', createTask: 'Create a Task', exploreRisk: 'Explore a risk', message: 'Message', askAnything: 'Ask Sage anything…', sending: 'Sending…', send: 'Send', thinking: 'Thinking…', thoughtProcess: 'Thought process', userMessage: 'User message', assistantMessage: 'Assistant message', eventStream: 'Event stream', copyEventStream: 'Copy event stream', backToConversations: 'Back to conversations', runtime: 'RUNTIME', chatRuntime: 'Chat runtime', eventStreamCopied: 'Copied {count} events.', copyFailedMessage: 'Copy failed; clipboard is unavailable.',
  chatUnavailable: 'This Chat is no longer available', chatRetention: 'The session may have passed retention.', chatEmptyTitle: 'Talk with your agent', selectConversation: 'Select a conversation, or start a new one', promoteTask: 'Promote to Task', retryRun: 'Retry run', artifact: 'Artifact', error: 'Error', tool: 'Tool', taskCardBody: 'Promote a message to a Task with run controls.', task: 'Task', noTasks: 'No Tasks yet', promoteImportant: 'Promote an important Chat message and it appears here.', goToChat: 'Go to Chat', allTasks: 'All tasks', revision: 'Revision', workflow: 'Workflow', target: 'Target', namespace: 'Namespace', taskQueue: 'Task queue', attempt: 'Attempt', controlsAuthorized: 'Authorized by the local workspace session.', taskControls: 'Task controls', timeline: 'Timeline', eventsCount: '{count} events', noProjectionEvents: 'No timeline events yet.', timelineProjectionLagging: 'Timeline is empty while catching up; refresh.', artifacts: 'Artifacts', artifactsPending: 'Artifacts appear here after a run commits output.', runningCount: '{count} running', taskDataUnavailable: 'Task data unavailable', refreshingTask: 'Refreshing task detail…', search: 'Search', searchTasks: 'Search tasks', searchTaskPlaceholder: 'Search by task, type, or target', allStatuses: 'All statuses', readingDurableState: 'Reading the latest state…', unavailable: 'Not available', projection: 'Projection', runLogs: 'Run logs', runLogsEmpty: 'No run events have been recorded for this task yet.', runLogsUnavailable: 'Run logs are unavailable right now.', loadMoreEvents: 'Load more events', selectAttempt: 'Select attempt', runLogAttemptOption: 'Attempt {index} · {time}', refsCount: '{count} refs', displayName: 'Display name', model: 'Model', catalogModel: 'Catalog model', customModelId: 'Custom model ID', adapterKind: 'Adapter kind', openAiCompatible: 'OpenAI-compatible', anthropic: 'Anthropic', baseUrl: 'Base URL', cancel: 'Cancel', saving: 'Saving…', pauseControl: 'Pause', resumeControl: 'Resume', cancelControl: 'Cancel', retryControl: 'Retry', taskTimeline: 'Task timeline', taskArtifacts: 'Task artifacts', statusRunning: 'Running', statusPaused: 'Paused', statusFailed: 'Failed', statusSucceeded: 'Succeeded', statusCancelled: 'Cancelled', statusEffectUnknown: 'Effect unknown', statusFresh: 'Fresh', statusStale: 'Stale', statusUnavailable: 'Unavailable', effectUnknownTitle: 'Effect unknown — confirm the outcome before continuing', effectUnknownBody: 'The run was interrupted before its result could be committed, so the system cannot confirm whether its effects actually took place. Retry and cancellation stay locked to prevent duplicate side effects.', effectUnknownGuidance: 'Ask a platform administrator to confirm the outcome through the effect resolution process; if no side effects occurred, you can simply start a new task.', staleAgeThreshold: 'No projection update within the freshness threshold',
runAgent: 'Run agent', defaultModelLabel: 'Default model', runAgentSaved: 'Run agent settings saved.', runAgentSaveFailed: 'Could not save run agent settings', runAgentUnavailable: 'Run agent settings unavailable', connectionReady: 'Package runs: workspace provider "{name}" ready', connectionUnavailable: 'Package runs: provider "{name}" unavailable', runAgentUnset: 'Not set', runAgentUnsetWarning: 'No default model set; package runs are rejected', workspaceProviderUnavailableOption: 'unavailable', chatNeedsProvider: 'A workspace provider is required before chatting; add one on the Providers page.', runtimeUnconfigured: 'Not selected', workspaceProviders: 'Workspace providers', addWorkspaceProvider: '+ Add workspace provider', editWorkspaceProvider: 'Edit workspace provider {name}', deleteWorkspaceProvider: 'Delete workspace provider {name}', noWorkspaceProviders: 'No workspace providers yet. Add one for package runs.', workspaceProviderSaved: 'Provider saved.', workspaceProviderDeleted: 'Provider deleted.', workspaceProviderSaveFailed: 'Could not save the workspace provider', workspaceProviderDeleteFailed: 'Could not delete the workspace provider', workspaceProviderRequired: 'Name, base URL, model required; API key on create.', deleteWorkspaceProviderConfirm: 'Delete this provider? Its stored credential is removed.', deleteWorkspaceProviderConfirmAction: 'Delete', deleteWorkspaceProviderCancel: 'Cancel', deleteDefaultModelWarning: 'Default model entry; set a new one after deleting.', workspaceProvidersUnavailable: 'Workspace providers unavailable', apiKeyServer: 'API key (sealed server-side, write-only)', apiKeyRequiredPlaceholder: 'Paste the provider API key; it is sealed and never readable again', apiKeyRotatePlaceholder: 'Enter a new key to rotate the stored credential', sourceUser: 'user', sourceDeploymentEnv: 'deployment env', credentialPresent: 'Credential stored', credentialMissing: 'No credential', saveWorkspaceProvider: 'Save workspace provider', providerDialogAddTitle: 'Add workspace provider', providerDialogEditTitle: 'Edit workspace provider', providerSearch: 'Provider search', modelSearch: 'Model search', searchProvidersPlaceholder: 'Search the models.dev catalog…', selectModelPlaceholder: 'Select a provider, then a model', noProviders: 'No matching providers', noModels: 'No matching models', catalogUnavailableManual: 'Model catalog unavailable — fill in the fields manually; adding still works.', catalogUpdatedNotice: 'Catalog changed; lists were reloaded.', refreshCatalog: 'Refresh catalog', catalogSyncing: 'Syncing…', catalogSyncReloaded: 'Catalog refreshed; lists reloaded.', catalogSyncRateLimited: 'The catalog was synced recently; retry in {seconds}s.', catalogSyncForbidden: 'Manual catalog sync requires the provider-catalog-admin role.', catalogSyncFailed: 'Could not refresh the catalog; try again later.',
  language: 'Language', chinese: '中文', english: 'English', languageSwitcher: 'Language',
  retryRequested: 'Retry requested.', promotionAccepted: 'Task promotion accepted.', viewCreatedTask: 'View task', taskControlFailed: 'Task control failed', taskRequestFailed: 'Task request failed', taskDetailFailed: 'Task detail failed', messageFailed: 'Message failed', retryFailed: 'Retry failed', promotionFailed: 'Promotion failed', recoveryFailed: 'Chat recovery failed', sessionHistoryUnavailable: 'Session history unavailable', createSessionFailed: 'Could not create Chat session', noPackages: 'No packages yet', noPackagesHint: 'Import a bundled example, or register via the API.', packageDataUnavailable: 'Package data unavailable', packageNotFound: 'Package not found', allPackages: 'All packages', releases: 'Releases', latestVersion: 'Latest version', releaseCount: '{count} releases', manifest: 'Manifest', assets: 'Assets', noAssets: 'No assets in this package', contentDigest: 'Content digest', lockDigest: 'Lock digest', compilerBuild: 'Compiler build', startRun: 'Start a run', startRunHint: 'Created from the latest release; blank params use defaults.', startingRun: 'Starting run…', startRunAction: 'Start run', runStarted: 'Run started', viewRun: 'View run', runStartFailed: 'Could not start the run', taskChoice: 'Task entry', paramDefaultOption: 'Default', numberParamInvalid: 'Param {name} must be a number', declaredInputs: 'Declared parameters', declaredDataSources: 'Data sources', declaredTasks: 'Task entries', outputPreviewUnavailable: 'Output is not available', manifestEntry: 'Entry prompt', modelRoute: 'Model route', skills: 'Skills', capabilities: 'Capabilities',
  newApp: '+ New App', createApp: 'Create App', creatingApp: 'Creating…', appId: 'App ID', appIdHint: 'Lowercase letters, digits, and hyphens; must start and end with a letter or digit.', appName: 'App name', appDescription: 'Description', appIdRequired: 'App ID is required', appNameRequired: 'App name is required', appIdInvalid: 'Invalid App ID format', createAppFailed: 'Could not create the App', uploadNewVersion: 'Upload new version', uploadVersion: 'Upload version', uploadingVersion: 'Uploading…', uploadHint: 'Choose a source package archive (tar / tar.gz / tgz / zip) to register a new version.', uploadArchiveFile: 'Source package archive', uploadArchiveRequired: 'Choose a source package archive', uploadArchiveInvalid: 'Unsupported archive. Use .tar, .tar.gz, .tgz, or .zip up to 8 MiB.', uploadArchiveTooLarge: 'Archive exceeds the 8 MiB upload limit.', outputPackage: 'Output package', outputFiles: 'Output files', downloadPackage: 'Download tar.gz', downloadFile: 'Download', failureDetail: 'Failure', uploadSucceeded: 'New version registered', uploadFailed: 'Could not upload the package', uploadFilesRequired: 'At least the app.yaml file is required', deleteApp: 'Delete App', deleteAppConfirm: 'Delete this app? This cannot be undone.', deleteAppConfirmAction: 'Delete App', deletingApp: 'Deleting…', deleteAppFailed: 'Could not delete the App', cancelAction: 'Cancel', uploadFiles: 'Package files (one per line, path then content)', uploadFilesPlaceholder: 'Paste files as JSON: { "app.yaml": "...", "prompts/system.md": "..." }', uploadFilesInvalid: 'Files must be a JSON object of path → content',
  importExamples: '+ Import example', importExamplesTitle: 'Import an example app', importExamplesHint: 'Registers the bundled example and its first release.', importExampleAction: 'Import', importingExample: 'Importing…', importExampleFailed: 'Could not import the example app',
} as const;

const zhMessages: { readonly [K in keyof typeof enMessages]: string } = {
  schedules: '定时任务', scheduleDataUnavailable: '定时任务数据不可用', scheduleAuthRequired: 'service token 未配置或未认证：请在服务端配置 SAGE_SERVICE_TOKEN / SAGE_SERVICE_TOKEN_HASHES 后刷新。', loadingSchedules: '正在加载定时任务…', noSchedules: '暂无定时任务', scheduleId: '调度', scheduleTrigger: '触发规则', scheduleBinding: 'Release 绑定', nextFire: '下次触发', actions: '操作', pause: '暂停', resume: '恢复', delete: '删除', confirmScheduleDelete: '删除该定时任务？', scheduleTriggerHistory: '触发历史', loadingTriggerHistory: '正在加载触发历史…', noTriggerEvents: '暂无触发事件', brandName: '思极', workspace: '工作区', configuration: '配置', chat: '聊天', tasks: '任务', providers: '服务商', packages: '应用', new: '新', localWorkspace: '本地工作区', systemRuntime: '系统运行时', localDevelopmentMode: '本地开发模式', mainNavigation: '主导航', accountMenu: '打开账户菜单', home: 'Sage 首页', collapseSidebar: '收起侧边栏', expandSidebar: '展开侧边栏', workspaceUnavailable: '工作区不可用', cannotOpenView: '无法打开此页面', runtimeFailed: 'Web 运行时启动失败', returnToHistory: '返回历史记录',
  conversationHistory: '对话历史', newChat: '+ 新建对话', creating: '创建中…', chatHistoryUnavailable: '对话历史不可用', searchSessionTitles: '搜索会话标题', searchTitles: '搜索标题', status: '状态', all: '全部', open: '开放', closed: '已关闭', refresh: '刷新', loadingRetainedSessions: '正在加载保留的会话', noRetainedSessions: '暂无历史对话', untitledChat: '未命名对话', noPersistedMessages: '尚无持久化消息', loadMore: '加载更多', loading: '加载中…', chatSessionHistory: '对话会话历史', historyViewLabel: '历史视图', conversationsTab: '对话', archiveTab: '归档', archivedSessionHistory: '已归档对话会话历史', archiveAction: '归档', unarchiveAction: '恢复', deleteAction: '删除', deleteConfirmWarning: '彻底删除该对话？此操作不可撤销。', confirmDelete: '彻底删除', noArchivedSessions: '暂无归档对话', archiveFailed: '归档对话失败', unarchiveFailed: '恢复对话失败', deleteSessionFailed: '删除对话失败', conversationArchived: '已归档', conversationRestored: '已恢复', conversationDeleted: '已彻底删除', archivedReadOnly: '对话已归档 · 只读', liveStreamConnected: '实时流已连接', connecting: '连接中…', streamReconnecting: '实时流重连中', session: '会话', events: '事件', run: '运行', ready: '就绪', openTaskWorkspace: '打开任务工作区', somethingNeedsAttention: '需要关注', dismissError: '关闭错误', dismissNotice: '关闭提示', recoveringConversation: '正在恢复对话', loadingEvents: '正在加载事件并重连实时流…', closedReadOnly: '会话已关闭 · 只读', composerReadOnly: '对话不可用 · 只读', tryAsking: '试着问问', summarizeProject: '总结项目', createTask: '创建任务', exploreRisk: '探索风险', message: '消息', askAnything: '想问 Sage 什么？', sending: '发送中…', send: '发送', thinking: '思考中…', thoughtProcess: '思考过程', userMessage: '用户消息', assistantMessage: '助手消息', eventStream: '事件流', copyEventStream: '复制事件流', backToConversations: '返回对话列表', runtime: '运行时', chatRuntime: '对话运行时', eventStreamCopied: '已复制 {count} 个事件', copyFailedMessage: '复制失败：剪贴板不可用',
  chatUnavailable: '此对话已不可用', chatRetention: '会话可能已超过保留期限', chatEmptyTitle: '和你的智能体对话', selectConversation: '选择一个对话，或点 + 新建', promoteTask: '提升为任务', retryRun: '重试运行', artifact: '产物', error: '错误', tool: '工具', taskCardBody: '将消息提升为任务，获得暂停、重试与取消控制', task: '任务', noTasks: '暂无任务', promoteImportant: '提升对话中的重要消息，任务会出现在这里', goToChat: '前往对话', allTasks: '全部任务', revision: '修订版本', workflow: '工作流', target: '目标', namespace: '命名空间', taskQueue: '任务队列', attempt: '尝试次数', controlsAuthorized: '由本地工作区会话授权', taskControls: '任务控制', timeline: '时间线', eventsCount: '{count} 个事件', noProjectionEvents: '暂无时间线事件。', timelineProjectionLagging: '时间线事件暂时为空，刷新可读取最新状态', artifacts: '产物', artifactsPending: '产物会在运行产出后显示在这里', runningCount: '{count} 个运行中', taskDataUnavailable: '任务数据不可用', refreshingTask: '正在刷新任务详情…', search: '搜索', searchTasks: '搜索任务', searchTaskPlaceholder: '按任务、类型或目标搜索', allStatuses: '所有状态', readingDurableState: '正在读取最新状态…', unavailable: '不可用', projection: '投影', runLogs: '运行日志', runLogsEmpty: '该任务尚未记录任何运行事件。', runLogsUnavailable: '运行日志暂时不可用。', loadMoreEvents: '加载更多事件', selectAttempt: '选择尝试', runLogAttemptOption: '尝试 {index} · {time}', refsCount: '{count} 个引用', displayName: '显示名称', model: '模型', catalogModel: '目录模型', customModelId: '自定义模型 ID', adapterKind: '适配器类型', openAiCompatible: 'OpenAI 兼容', anthropic: 'Anthropic', baseUrl: '基础 URL', cancel: '取消', saving: '保存中…', pauseControl: '暂停', resumeControl: '继续', cancelControl: '取消', retryControl: '重试', taskTimeline: '任务时间线', taskArtifacts: '任务产物', statusRunning: '运行中', statusPaused: '已暂停', statusFailed: '失败', statusSucceeded: '已成功', statusCancelled: '已取消', statusEffectUnknown: '效果未知', statusFresh: '新鲜', statusStale: '已过期', statusUnavailable: '不可用', effectUnknownTitle: '效果未知：需要确认结果后才能继续', effectUnknownBody: '任务在一次执行后中断，结果未确认提交，系统无法判断该次执行是否已实际生效。为避免同一操作被重复执行、产生重复副作用，重试与取消暂时锁定。', effectUnknownGuidance: '请联系平台管理员通过效果裁决流程确认本次执行的结果；确认没有产生副作用时，也可以直接重新发起新任务。', staleAgeThreshold: '距最近一次状态更新已超过新鲜度阈值',
runAgent: '运行 Agent', defaultModelLabel: '默认模型', runAgentSaved: '运行 Agent 设置已保存。', runAgentSaveFailed: '保存运行 Agent 设置失败', runAgentUnavailable: '运行 Agent 设置不可用', connectionReady: '包运行：工作区 provider「{name}」就绪', connectionUnavailable: '包运行：provider「{name}」不可用', runAgentUnset: '未设置', runAgentUnsetWarning: '未设默认模型，包运行将被拒绝', workspaceProviderUnavailableOption: '不可用', chatNeedsProvider: '需要先有一个工作区 provider 才能开始对话；可在「服务商」页添加。', runtimeUnconfigured: '未选择', workspaceProviders: '工作区 provider', addWorkspaceProvider: '+ 添加工作区 provider', editWorkspaceProvider: '编辑工作区 provider {name}', deleteWorkspaceProvider: '删除工作区 provider {name}', noWorkspaceProviders: '暂无工作区 provider，添加后可用于包运行', workspaceProviderSaved: 'provider 已保存', workspaceProviderDeleted: 'provider 已删除', workspaceProviderSaveFailed: '保存工作区 provider 失败', workspaceProviderDeleteFailed: '删除工作区 provider 失败', workspaceProviderRequired: '名称、URL、模型必填；新建还需 API 密钥', deleteWorkspaceProviderConfirm: '删除该 provider？凭据将一并删除。', deleteWorkspaceProviderConfirmAction: '确认删除', deleteWorkspaceProviderCancel: '取消', deleteDefaultModelWarning: '该条目是包运行默认模型；删除后需重新设置', workspaceProvidersUnavailable: '工作区 provider 不可用', apiKeyServer: 'API 密钥（服务端密封，只写不读）', apiKeyRequiredPlaceholder: '粘贴 provider API 密钥；将被密封且此后不可读取', apiKeyRotatePlaceholder: '输入新密钥以轮换已托管凭据', sourceUser: '用户', sourceDeploymentEnv: '部署环境', credentialPresent: '凭据已托管', credentialMissing: '无凭据', saveWorkspaceProvider: '保存工作区 provider', providerDialogAddTitle: '添加工作区 provider', providerDialogEditTitle: '编辑工作区 provider', providerSearch: 'Provider 搜索', modelSearch: '模型搜索', searchProvidersPlaceholder: '从 models.dev 目录搜索…', selectModelPlaceholder: '先选择 provider，再选择模型', noProviders: '没有匹配的 provider', noModels: '没有匹配的模型', catalogUnavailableManual: '模型目录不可用——可手工填写以下字段，添加不受影响。', catalogUpdatedNotice: '模型目录已更新，列表已重新加载', refreshCatalog: '刷新目录', catalogSyncing: '同步中…', catalogSyncReloaded: '目录已刷新，列表已重新加载', catalogSyncRateLimited: '目录刚同步过，请在 {seconds} 秒后重试。', catalogSyncForbidden: '手动同步目录需要 provider-catalog-admin 角色。', catalogSyncFailed: '目录刷新失败，请稍后重试。',
  language: '语言', chinese: '中文', english: 'English', languageSwitcher: '语言', retryRequested: '已请求重试', promotionAccepted: '任务提升已接受', viewCreatedTask: '查看任务', taskControlFailed: '任务控制失败', taskRequestFailed: '任务请求失败', taskDetailFailed: '任务详情加载失败', messageFailed: '消息发送失败', retryFailed: '重试失败', promotionFailed: '提升失败', recoveryFailed: '对话恢复失败', sessionHistoryUnavailable: '对话历史不可用', createSessionFailed: '无法创建对话会话', noPackages: '暂无应用', noPackagesHint: '可导入内置示例，或通过 API 登记应用包', packageDataUnavailable: '应用数据不可用', packageNotFound: '应用不存在', allPackages: '全部应用', releases: 'Release', latestVersion: '最新版本', releaseCount: '{count} 个 Release', manifest: '清单', assets: '资产', noAssets: '该应用没有资产', contentDigest: '内容摘要', lockDigest: '锁摘要', compilerBuild: '编译器构建', startRun: '发起运行', startRunHint: '基于最新 Release 创建，留空用默认参数', startingRun: '正在发起运行…', startRunAction: '发起运行', runStarted: '运行已发起', viewRun: '查看运行', runStartFailed: '发起运行失败', taskChoice: '任务入口', paramDefaultOption: '默认', numberParamInvalid: '参数 {name} 必须是数字', declaredInputs: '声明参数', declaredDataSources: '数据源', declaredTasks: '任务入口', outputPreviewUnavailable: '输出暂不可用', manifestEntry: '入口提示词', modelRoute: '模型路由', skills: '技能', capabilities: '能力',
  newApp: '+ 新建应用', createApp: '新建应用', creatingApp: '创建中…', appId: '应用 ID', appIdHint: '小写字母、数字与连字符，须以字母或数字开头与结尾。', appName: '应用名称', appDescription: '描述', appIdRequired: '应用 ID 为必填项', appNameRequired: '应用名称为必填项', appIdInvalid: '应用 ID 格式不正确', createAppFailed: '创建应用失败', uploadNewVersion: '上传新版本', uploadVersion: '上传版本', uploadingVersion: '上传中…', uploadHint: '选择源包压缩文件（tar / tar.gz / tgz / zip）登记为新版本', uploadArchiveFile: '源包压缩文件', uploadArchiveRequired: '请选择源包压缩文件', uploadArchiveInvalid: '不支持的压缩包。请使用 .tar、.tar.gz、.tgz 或 .zip，且不超过 8 MiB。', uploadArchiveTooLarge: '压缩包超过 8 MiB 上限。', outputPackage: '输出包', outputFiles: '输出文件', downloadPackage: '下载 tar.gz', downloadFile: '下载', failureDetail: '失败原因', uploadSucceeded: '新版本已登记', uploadFailed: '上传应用包失败', uploadFilesRequired: '至少需要 app.yaml 文件', deleteApp: '删除应用', deleteAppConfirm: '删除该应用？此操作不可撤销。', deleteAppConfirmAction: '删除应用', deletingApp: '删除中…', deleteAppFailed: '删除应用失败', cancelAction: '取消', uploadFiles: '应用包文件（JSON：路径 → 内容）', uploadFilesPlaceholder: '粘贴 JSON：{ "app.yaml": "...", "prompts/system.md": "..." }', uploadFilesInvalid: '文件必须是「路径 → 内容」的 JSON 对象',
  importExamples: '+ 导入示例项目', importExamplesTitle: '导入示例应用', importExamplesHint: '一键登记内置示例并登记首个 Release', importExampleAction: '导入', importingExample: '导入中…', importExampleFailed: '导入示例应用失败',
};

export const messages = { en: enMessages, 'zh-CN': zhMessages } as const;
export type MessageKey = keyof typeof enMessages;
export type MessageValues = Readonly<Record<string, string | number>>;
export const messageKeys = Object.keys(enMessages) as MessageKey[];

export function normalizeLocale(value: unknown): Locale | undefined {
  if (typeof value !== 'string') return undefined;
  const normalized = value.trim().toLowerCase();
  if (/^zh(?:-|$)/.test(normalized)) return 'zh-CN';
  if (/^en(?:-|$)/.test(normalized)) return 'en';
  return undefined;
}

export interface LocaleNavigator { readonly languages?: readonly string[]; readonly language?: string }
export interface LocaleStorage { getItem(key: string): string | null; setItem(key: string, value: string): void }

export function resolveInitialLocale(storage?: LocaleStorage, navigatorLike?: LocaleNavigator): Locale {
  try { const persisted = normalizeLocale(storage?.getItem(LOCALE_STORAGE_KEY)); if (persisted) return persisted; } catch { /* isolated storage failure */ }
  try {
    const candidates = [...(navigatorLike?.languages ?? []), navigatorLike?.language].filter((value): value is string => typeof value === 'string' && value.length > 0);
    for (const candidate of candidates) { const detected = normalizeLocale(candidate); if (detected) return detected; }
  } catch { /* isolated language API failure */ }
  return 'zh-CN';
}

function browserStorage(): LocaleStorage | undefined { try { return typeof window === 'undefined' ? undefined : window.localStorage; } catch { return undefined; } }
function browserNavigator(): LocaleNavigator | undefined { try { return typeof navigator === 'undefined' ? undefined : navigator; } catch { return undefined; } }
function interpolate(template: string, values?: MessageValues): string { return values ? template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`)) : template; }

export interface LocaleContextValue { readonly locale: Locale; readonly setLocale: (locale: Locale) => void; readonly t: (key: MessageKey, values?: MessageValues) => string; readonly formatDateTime: (value: string | Date) => string; readonly formatTime: (value: string | Date) => string; readonly formatCompact: (value: string | Date) => string }
/** 列表行紧凑时间：双语同构的 MM-DD HH:mm（定宽，防徽章/日期互撞）；完整时间戳由 hover title 或详情页承担。 */
const compactDateTime = (value: string | Date): string => {
  const parts = new Intl.DateTimeFormat('en', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(new Date(value));
  const take = (type: string): string => parts.find((part) => part.type === type)?.value ?? '';
  return `${take('month')}-${take('day')} ${take('hour')}:${take('minute')}`;
};
const fallback: LocaleContextValue = { locale: 'en', setLocale: () => undefined, t: (key, values) => interpolate(enMessages[key], values), formatDateTime: (value) => new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)), formatTime: (value) => new Intl.DateTimeFormat('en', { hour: '2-digit', minute: '2-digit' }).format(new Date(value)), formatCompact: compactDateTime };
const LocaleContext = createContext<LocaleContextValue>(fallback);

export function LocaleProvider({ children }: { readonly children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => resolveInitialLocale(browserStorage(), browserNavigator()));
  useEffect(() => { document.documentElement.lang = locale; }, [locale]);
  const setLocale = (next: Locale) => { setLocaleState(next); try { browserStorage()?.setItem(LOCALE_STORAGE_KEY, next); } catch { /* best effort persistence */ } };
  const value = useMemo<LocaleContextValue>(() => ({ locale, setLocale, t: (key, values) => interpolate(messages[locale][key], values), formatDateTime: (value) => new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)), formatTime: (value) => new Intl.DateTimeFormat(locale, { hour: '2-digit', minute: '2-digit' }).format(new Date(value)), formatCompact: compactDateTime }), [locale]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}
export function useLocale(): LocaleContextValue { return useContext(LocaleContext); }
