import {act,create} from 'react-test-renderer';
import {describe,expect,it,vi} from 'vitest';
import {TasksApp,type TaskViewModel} from './tasks.js';

(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
const task:TaskViewModel={taskId:'task-ui',taskType:'sage.agent-task.v1',workflowId:'workflow-ui',targetId:'target-ui',attempt:1,status:'running',revision:1,projectionUpdatedAt:'2026-08-12T00:00:00.000Z',freshness:'stale',staleReason:'age_threshold_exceeded',targetSnapshot:{targetId:'target-ui',environment:'development',namespace:'sage-dev',taskQueue:'queue-ui'}};
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});
const flush=()=>new Promise((resolve)=>setTimeout(resolve,0));
describe('P6 mounted Task UI interactions',()=>{
  it('uses cookie/session auth, renders stale detail/timeline/artifact, and refreshes after 202 controls without raw target',async()=>{
    const calls:{url:string;init?:RequestInit}[]=[];const fetcher=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);calls.push({url,...(init?{init}:{})});if(url.endsWith('/v1/tasks'))return response({tasks:[task]});if(url.endsWith('/events'))return response({events:[{eventId:'event-ui',sequence:1,kind:'agent',type:'agent.task.running',occurredAt:'2026-08-12T00:00:01.000Z',payload:{}}]});if(url.endsWith('/artifacts'))return response({artifacts:[{artifactId:'output',artifactRef:'artifact://tasks/task-ui/output',name:'output.txt',mediaType:'text/plain'}]});if(init?.method==='POST')return response(task,202);return response(task);}) as typeof fetch;
    let tree!:ReturnType<typeof create>;await act(async()=>{tree=create(<TasksApp fetcher={fetcher} taskId="task-ui" sessionId="session-ui"/>);await flush();await flush();});expect(tree.root.findByProps({children:'task-ui'})).toBeTruthy();expect(calls.filter((call)=>call.url.endsWith('/v1/tasks/task-ui'))).toHaveLength(1);expect(tree.root.findByProps({'data-testid':'projection-freshness'}).findByType('strong').children).toContain('stale');expect(tree.root.findByProps({'aria-label':'Task timeline'})).toBeTruthy();expect(tree.root.findByProps({'aria-label':'Task artifacts'})).toBeTruthy();
    await act(async()=>{tree.root.findByProps({children:'Cancel'}).props.onClick();await flush();});const control=calls.find((call)=>call.url.endsWith('/cancel'));expect(control?.init).toMatchObject({method:'POST',credentials:'include'});expect(control?.init?.headers).not.toHaveProperty('x-authentication-id');expect(control?.init?.body).toBe('{}');expect(JSON.stringify(calls)).not.toMatch(/targetId|endpoint|namespace/);expect(calls.filter((call)=>call.url.endsWith('/v1/tasks/task-ui')).length).toBe(2);await act(async()=>tree.unmount());
  });
  it('renders authenticated API errors instead of treating a 401 body as Task data',async()=>{const fetchMock=vi.fn(async(_input:RequestInfo|URL,_init?:RequestInit)=>{void _input;void _init;return response({error:{code:'TASK_AUTHENTICATION_REQUIRED',message:'Sign in required'}},401);});const fetcher=fetchMock as unknown as typeof fetch;let tree!:ReturnType<typeof create>;await act(async()=>{tree=create(<TasksApp fetcher={fetcher}/>);await flush();});expect(tree.root.findByProps({role:'alert'}).children.join('')).toContain('Sign in required');expect(fetchMock.mock.calls[0]?.[1]).toMatchObject({credentials:'include'});await act(async()=>tree.unmount());});
});
