import { useEffect, useState } from "react";

/**
 * Query-driven client router (spec §3.1).
 *
 * The app never changes path; all navigation happens through the query string
 * of the current path. Internal links are generated by `workspaceHref`, and
 * navigation completes via `history.pushState` plus the `sage:navigate`
 * custom event. `popstate` and `sage:navigate` both refresh route state.
 */

export type WorkspaceView = "chat" | "tasks" | "providers" | "packages" | "schedules";

export interface RouteState {
  view: WorkspaceView;
  session?: string | undefined;
  task?: string | undefined;
  package?: string | undefined;
}

export const NAVIGATE_EVENT = "sage:navigate";

const WORKSPACE_VIEWS: readonly WorkspaceView[] = ["chat", "tasks", "providers", "packages", "schedules"];

function isWorkspaceView(value: string | null): value is WorkspaceView {
  return value !== null && (WORKSPACE_VIEWS as readonly string[]).includes(value);
}

/** Unknown or missing `view` always falls back to Chat (spec §3.1 rule 1). */
export function parseRoute(search: string): RouteState {
  const params = new URLSearchParams(search);
  const viewParam = params.get("view");
  const route: RouteState = { view: isWorkspaceView(viewParam) ? viewParam : "chat" };
  const session = params.get("session");
  if (session) route.session = session;
  const task = params.get("task");
  if (task) route.task = task;
  const pkg = params.get("package");
  if (pkg) route.package = pkg;
  return route;
}

/**
 * Build an internal link (spec §3.1 rule 2): Chat never writes `view`;
 * only parameters with values are written, in a fixed order.
 */
export function workspaceHref(route: RouteState): string {
  const params = new URLSearchParams();
  if (route.view !== "chat") params.set("view", route.view);
  if (route.task) params.set("task", route.task);
  if (route.package) params.set("package", route.package);
  if (route.session) params.set("session", route.session);
  const query = params.toString();
  return query ? `?${query}` : "/";
}

export function navigateTo(href: string): void {
  window.history.pushState(null, "", href);
  window.dispatchEvent(new Event(NAVIGATE_EVENT));
}

/** Current route state; re-parses on popstate and sage:navigate (spec §3.1 rule 5). */
export function useRoute(): RouteState {
  const [route, setRoute] = useState<RouteState>(() => parseRoute(window.location.search));
  useEffect(() => {
    const sync = () => setRoute(parseRoute(window.location.search));
    window.addEventListener("popstate", sync);
    window.addEventListener(NAVIGATE_EVENT, sync);
    return () => {
      window.removeEventListener("popstate", sync);
      window.removeEventListener(NAVIGATE_EVENT, sync);
    };
  }, []);
  return route;
}

/** Minimal structural view of a click event, so the predicate stays testable. */
export interface ClickEventLike {
  button: number;
  metaKey: boolean;
  ctrlKey: boolean;
  shiftKey: boolean;
  altKey: boolean;
  defaultPrevented: boolean;
}

/**
 * Whether an anchor click should become client-side navigation
 * (spec §3.1 rules 3-4). Everything not explicitly safe is left to the
 * browser: modifier/non-left clicks, target, download, `#`, mailto/tel/data
 * URLs, external URLs, and links to a different path.
 */
export function shouldInterceptClick(anchor: HTMLAnchorElement, event: ClickEventLike): boolean {
  if (event.defaultPrevented) return false;
  if (event.button !== 0) return false;
  if (event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return false;
  if (anchor.target && anchor.target !== "_self") return false;
  if (anchor.hasAttribute("download")) return false;
  const rawHref = anchor.getAttribute("href");
  if (!rawHref) return false;
  if (rawHref.startsWith("#")) return false;
  const lowered = rawHref.trim().toLowerCase();
  if (lowered.startsWith("mailto:") || lowered.startsWith("tel:") || lowered.startsWith("data:")) return false;
  let url: URL;
  try {
    url = new URL(anchor.href);
  } catch {
    return false;
  }
  if (url.origin !== window.location.origin) return false;
  if (url.pathname !== window.location.pathname) return false;
  return true;
}

/**
 * App-level global click interception (spec §3.1 rules 3-4): same-origin,
 * same-path, plain left clicks on internal links become client-side
 * navigation; everything else passes through untouched.
 */
export function useGlobalLinkInterceptor(): void {
  useEffect(() => {
    const onClick = (event: MouseEvent) => {
      if (!(event.target instanceof Element)) return;
      const anchor = event.target.closest("a[href]");
      if (!(anchor instanceof HTMLAnchorElement)) return;
      if (!shouldInterceptClick(anchor, event)) return;
      event.preventDefault();
      const rawHref = anchor.getAttribute("href");
      if (rawHref) navigateTo(rawHref);
    };
    document.addEventListener("click", onClick);
    return () => document.removeEventListener("click", onClick);
  }, []);
}
