import { createHash } from 'node:crypto';
import { Pool, type PoolClient, type PoolConfig, type QueryResultRow } from 'pg';
import type { AdapterHealth, KmsPort, ObjectStorePort, ProductionCheckpointDescriptor, ProductionCheckpointLifecyclePort } from '@sage/platform-ports';
import { sha256Digest } from '@sage/agent-contracts';
import { withDecryptedEnvelope } from '@sage/production-governance';
interface CheckpointRow extends QueryResultRow { tenant_id: string; operation_id: string; candidate_digest: string; task_id: string; run_id: string; attempt_id: string; spec_digest: string; sequence: string | number; state_schema: string; engine_codec: string; runtime_contract_major: number; effect_receipt_refs: string[]; usage_receipt_refs: string[]; temporary_body_ref: string; body_object_ref: string | null; checkpoint_ref: string | null; body_digest: string; envelope_key_ref: string; key_version: string; key_rotation: string | number; retention_class: string; legal_hold: boolean; state: 'pending' | 'committed' | 'quarantined' | 'tombstoned' | 'backup_expired'; fence_epoch: string | number; committed_at: Date | string | null; backup_expires_at: Date | string | null }
const digest = (body: Uint8Array): string => `sha256:${createHash('sha256').update(body).digest('hex')}`;
const refsValid = (refs: readonly string[]): boolean => refs.length === new Set(refs).size && refs.every(ref => typeof ref === 'string' && ref.length > 0);
const descriptorDigest = (input: ProductionCheckpointDescriptor & { readonly body?: Uint8Array }): string => sha256Digest(Object.fromEntries(Object.entries({ schemaVersion: '1', ...input, effectReceiptRefs: [...input.effectReceiptRefs].sort(), usageReceiptRefs: [...input.usageReceiptRefs].sort() }).filter(([key]) => key !== 'body')));
export class PostgresCheckpointLifecycleStore implements ProductionCheckpointLifecyclePort {
  readonly #pool: Pool;
  constructor(config: PoolConfig | Pool, private readonly objectStore: ObjectStorePort, private readonly kms: KmsPort) { this.#pool = config instanceof Pool ? config : new Pool(config); }
  async #tx<T>(tenantId: string, principalRef: string, work: (client: PoolClient) => Promise<T>): Promise<T> { const client = await this.#pool.connect(); try { await client.query('BEGIN'); await client.query('SELECT sage_security.set_request_context($1,$2)', [tenantId, principalRef]); const result = await work(client); await client.query('COMMIT'); return result; } catch (cause) { await client.query('ROLLBACK').catch(() => undefined); throw cause; } finally { client.release(); } }
  #assertDescriptor(input: ProductionCheckpointDescriptor): void { if (!/^sha256:[a-f0-9]{64}$/.test(input.specDigest) || !/^sha256:[a-f0-9]{64}$/.test(input.bodyDigest) || !Number.isSafeInteger(input.sequence) || input.sequence < 1 || !Number.isSafeInteger(input.runtimeContractMajor) || input.runtimeContractMajor < 1 || !refsValid(input.effectReceiptRefs) || !refsValid(input.usageReceiptRefs) || input.effectReceiptRefs.length + input.usageReceiptRefs.length < 1) throw new Error('CHECKPOINT_DESCRIPTOR_INVALID'); }
  #matches(row: CheckpointRow, input: ProductionCheckpointDescriptor): boolean { return row.tenant_id === input.tenantId && row.operation_id === input.operationId && row.task_id === input.taskId && row.run_id === input.runId && row.attempt_id === input.attemptId && row.spec_digest === input.specDigest && Number(row.sequence) === input.sequence && row.state_schema === input.stateSchema && row.engine_codec === input.engineCodec && row.runtime_contract_major === input.runtimeContractMajor && row.body_digest === input.bodyDigest && row.retention_class === input.retentionClass && sha256Digest([...row.effect_receipt_refs].sort()) === sha256Digest([...input.effectReceiptRefs].sort()) && sha256Digest([...row.usage_receipt_refs].sort()) === sha256Digest([...input.usageReceiptRefs].sort()); }
  async #lineageExists(client: PoolClient, input: ProductionCheckpointDescriptor): Promise<boolean> { for (const ref of input.effectReceiptRefs) if ((await client.query(`SELECT 1 FROM agent_effect_receipts WHERE tenant_id=$1 AND receipt->>'receiptRef'=$2`, [input.tenantId, ref])).rowCount !== 1) return false; for (const ref of input.usageReceiptRefs) if ((await client.query(`SELECT 1 FROM agent_usage_receipts WHERE tenant_id=$1 AND receipt->>'receiptRef'=$2`, [input.tenantId, ref])).rowCount !== 1) return false; return true; }
  async stageCheckpoint(input: ProductionCheckpointDescriptor & { readonly body: Uint8Array }) {
    this.#assertDescriptor(input); if (digest(input.body) !== input.bodyDigest) throw new Error('CHECKPOINT_DIGEST_MISMATCH');
    const existing = await this.#tx(input.tenantId, 'principal://checkpoint-store', async client => (await client.query<CheckpointRow>('SELECT * FROM agent_checkpoint_commit_operations WHERE tenant_id=$1 AND operation_id=$2', [input.tenantId, input.operationId])).rows[0]);
    if (existing) { if (!this.#matches(existing, input)) throw new Error('CHECKPOINT_CONFLICT'); return { state: existing.state === 'committed' ? 'committed' as const : 'pending' as const, operationId: input.operationId, fenceEpoch: Number(existing.fence_epoch), ...(existing.checkpoint_ref ? { checkpointRef: existing.checkpoint_ref } : {}) }; }
    const context = { tenantId: input.tenantId, operationId: input.operationId, bodyDigest: input.bodyDigest };
    const encrypted = await this.kms.encrypt({ keyRef: input.keyRef, tenantId: input.tenantId, plaintext: input.body, context });
    try {
      const temporary = await this.objectStore.putTemporary({ tenantId: input.tenantId, operationId: input.operationId, ciphertext: encrypted.ciphertext, digest: input.bodyDigest });
      await this.#tx(input.tenantId, 'principal://checkpoint-store', async client => { if (!await this.#lineageExists(client, input)) throw new Error('CHECKPOINT_LINEAGE_INVALID'); await client.query(`INSERT INTO agent_checkpoint_commit_operations(tenant_id,operation_id,candidate_digest,task_id,run_id,attempt_id,spec_digest,sequence,state_schema,engine_codec,runtime_contract_major,effect_receipt_refs,usage_receipt_refs,temporary_body_ref,body_digest,envelope_key_ref,key_version,retention_class,state,fence_epoch) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,'pending',1)`, [input.tenantId, input.operationId, descriptorDigest(input), input.taskId, input.runId, input.attemptId, input.specDigest, input.sequence, input.stateSchema, input.engineCodec, input.runtimeContractMajor, JSON.stringify(input.effectReceiptRefs), JSON.stringify(input.usageReceiptRefs), temporary.temporaryRef, input.bodyDigest, input.keyRef, encrypted.keyVersion, input.retentionClass]); await client.query(`INSERT INTO agent_checkpoint_commit_outbox(tenant_id,operation_id,fence_epoch,state) VALUES($1,$2,1,'pending')`, [input.tenantId, input.operationId]); });
      return { state: 'pending' as const, operationId: input.operationId, fenceEpoch: 1 };
    } finally { encrypted.ciphertext.fill(0); }
  }
  async finalizeCheckpoint(input: { readonly tenantId: string; readonly operationId: string; readonly fenceEpoch: number }) {
    const row = await this.#tx(input.tenantId, 'principal://checkpoint-finalizer', async client => (await client.query<CheckpointRow>('SELECT * FROM agent_checkpoint_commit_operations WHERE tenant_id=$1 AND operation_id=$2', [input.tenantId, input.operationId])).rows[0]);
    if (!row) return { state: 'quarantined' as const, reason: 'CHECKPOINT_NOT_FOUND' }; if (row.state === 'committed' && row.checkpoint_ref) return { state: 'committed' as const, checkpointRef: row.checkpoint_ref }; if (row.state !== 'pending' || Number(row.fence_epoch) !== input.fenceEpoch) return { state: 'quarantined' as const, reason: 'CHECKPOINT_FENCE_LOST' };
    const checkpointRef = `checkpoint://sealed/${row.candidate_digest.slice(7)}`; const bodyObjectRef = `checkpoint-body://committed/${input.tenantId}/${input.operationId}/${row.body_digest.slice(7)}`;
    try { await this.objectStore.promote({ tenantId: input.tenantId, temporaryRef: row.temporary_body_ref, committedRef: bodyObjectRef, expectedDigest: row.body_digest, fenceEpoch: input.fenceEpoch }); } catch { await this.#quarantine(input.tenantId, input.operationId, 'OBJECT_PROMOTE_UNVERIFIABLE'); return { state: 'quarantined' as const, reason: 'OBJECT_PROMOTE_UNVERIFIABLE' }; }
    return this.#tx(input.tenantId, 'principal://checkpoint-finalizer', async client => { const updated = await client.query(`UPDATE agent_checkpoint_commit_operations SET state='committed',checkpoint_ref=$4,body_object_ref=$5,committed_at=clock_timestamp() WHERE tenant_id=$1 AND operation_id=$2 AND fence_epoch=$3 AND state='pending'`, [input.tenantId, input.operationId, input.fenceEpoch, checkpointRef, bodyObjectRef]); if (updated.rowCount !== 1) return { state: 'quarantined' as const, reason: 'CHECKPOINT_METADATA_CONFLICT' }; await client.query(`UPDATE agent_checkpoint_commit_outbox SET state='published',published_at=clock_timestamp() WHERE tenant_id=$1 AND operation_id=$2`, [input.tenantId, input.operationId]); return { state: 'committed' as const, checkpointRef }; });
  }
  async #quarantine(tenantId: string, operationId: string, reason: string): Promise<void> { await this.#tx(tenantId, 'reconciler://checkpoint', async client => { await client.query(`UPDATE agent_checkpoint_commit_operations SET state='quarantined' WHERE tenant_id=$1 AND operation_id=$2 AND state='pending'`, [tenantId, operationId]); await client.query(`UPDATE agent_checkpoint_commit_outbox SET state='quarantined' WHERE tenant_id=$1 AND operation_id=$2`, [tenantId, operationId]); await client.query(`INSERT INTO agent_security_audit(tenant_id,category,decision,reason_code,actor_ref,correlation,authority_digest,occurred_at) VALUES($1,'reconcile','quarantined',$2,'reconciler://checkpoint',$3,$4,clock_timestamp())`, [tenantId, reason, { operation_ref: operationId }, sha256Digest([operationId, reason])]); }); }
  async resumeCheckpoint(input: Omit<ProductionCheckpointDescriptor, 'operationId' | 'bodyDigest' | 'keyRef' | 'retentionClass'> & { readonly checkpointRef: string; readonly expectedBodyDigest: string; readonly now: string }): Promise<Uint8Array | undefined> {
    const row = await this.#tx(input.tenantId, 'principal://checkpoint-reader', async client => (await client.query<CheckpointRow>(`SELECT * FROM agent_checkpoint_commit_operations WHERE tenant_id=$1 AND checkpoint_ref=$2 AND state='committed'`, [input.tenantId, input.checkpointRef])).rows[0]);
    if (!row || !row.body_object_ref || row.body_digest !== input.expectedBodyDigest || row.task_id !== input.taskId || row.run_id !== input.runId || row.attempt_id !== input.attemptId || row.spec_digest !== input.specDigest || Number(row.sequence) !== input.sequence || row.state_schema !== input.stateSchema || row.engine_codec !== input.engineCodec || row.runtime_contract_major !== input.runtimeContractMajor || sha256Digest([...row.effect_receipt_refs].sort()) !== sha256Digest([...input.effectReceiptRefs].sort()) || sha256Digest([...row.usage_receipt_refs].sort()) !== sha256Digest([...input.usageReceiptRefs].sort()) || !refsValid(input.effectReceiptRefs) || !refsValid(input.usageReceiptRefs)) return undefined;
    const cipher = await this.objectStore.get({ tenantId: input.tenantId, committedRef: row.body_object_ref }); if (!cipher) return undefined;
    const context = { tenantId: input.tenantId, operationId: row.operation_id, bodyDigest: row.body_digest };
    return withDecryptedEnvelope(this.kms, { keyRef: row.envelope_key_ref, tenantId: input.tenantId, ciphertext: cipher, context }, async plain => { if (digest(plain) !== row.body_digest) throw new Error('CHECKPOINT_DIGEST_MISMATCH'); return new Uint8Array(plain); });
  }
  async reconcileCheckpoint(input: { readonly tenantId: string; readonly now: string; readonly limit: number }): Promise<readonly string[]> { if (!Number.isInteger(input.limit) || input.limit < 1 || input.limit > 1000) throw new Error('RECONCILE_LIMIT_INVALID'); return this.#tx(input.tenantId, 'reconciler://checkpoint', async client => (await client.query<CheckpointRow>(`SELECT * FROM agent_checkpoint_commit_operations WHERE tenant_id=$1 AND state IN ('pending','quarantined') AND created_at<=$2 ORDER BY created_at LIMIT $3 FOR UPDATE SKIP LOCKED`, [input.tenantId, input.now, input.limit])).rows.map(row => row.operation_id)); }
  async setCheckpointLegalHold(input: { readonly tenantId: string; readonly checkpointRef: string; readonly active: boolean; readonly actorRef: string }): Promise<void> { await this.#tx(input.tenantId, input.actorRef, async client => { const updated = await client.query(`UPDATE agent_checkpoint_commit_operations SET legal_hold=$3 WHERE tenant_id=$1 AND checkpoint_ref=$2 AND state IN ('committed','tombstoned')`, [input.tenantId, input.checkpointRef, input.active]); if (updated.rowCount !== 1) throw new Error('CHECKPOINT_NOT_FOUND'); await client.query(`INSERT INTO agent_security_audit(tenant_id,category,decision,reason_code,actor_ref,correlation,authority_digest,occurred_at) VALUES($1,'reconcile',$2,'CHECKPOINT_LEGAL_HOLD',$3,$4,$5,clock_timestamp())`, [input.tenantId, input.active ? 'held' : 'released', input.actorRef, { checkpoint_ref: input.checkpointRef }, sha256Digest(input)]); }); }
  async rotateCheckpointKey(input: { readonly tenantId: string; readonly checkpointRef: string; readonly currentKeyRef: string; readonly nextKeyRef: string }): Promise<void> { const row = await this.#tx(input.tenantId, 'principal://checkpoint-key-rotation', async client => (await client.query<CheckpointRow>(`SELECT * FROM agent_checkpoint_commit_operations WHERE tenant_id=$1 AND checkpoint_ref=$2 AND state='committed'`, [input.tenantId, input.checkpointRef])).rows[0]); if (!row || !row.body_object_ref || row.envelope_key_ref !== input.currentKeyRef) throw new Error('CHECKPOINT_KEY_ROTATION_CONFLICT'); const cipher = await this.objectStore.get({ tenantId: input.tenantId, committedRef: row.body_object_ref }); if (!cipher) throw new Error('CHECKPOINT_BODY_UNAVAILABLE'); const context = { tenantId: input.tenantId, operationId: row.operation_id, bodyDigest: row.body_digest }; const plain = await this.kms.decrypt({ keyRef: row.envelope_key_ref, tenantId: input.tenantId, ciphertext: cipher, context }); try { if (digest(plain.plaintext) !== row.body_digest) throw new Error('CHECKPOINT_DIGEST_MISMATCH'); const encrypted = await this.kms.encrypt({ keyRef: input.nextKeyRef, tenantId: input.tenantId, plaintext: plain.plaintext, context }); try { const rotation = Number(row.key_rotation) + 1; const temp = await this.objectStore.putTemporary({ tenantId: input.tenantId, operationId: `${row.operation_id}-key-${rotation}`, ciphertext: encrypted.ciphertext, digest: row.body_digest }); const nextObject = `${row.body_object_ref}/key-${rotation}`; await this.objectStore.promote({ tenantId: input.tenantId, temporaryRef: temp.temporaryRef, committedRef: nextObject, expectedDigest: row.body_digest, fenceEpoch: Number(row.fence_epoch) }); await this.#tx(input.tenantId, 'principal://checkpoint-key-rotation', async client => { const updated = await client.query(`UPDATE agent_checkpoint_commit_operations SET body_object_ref=$4,envelope_key_ref=$5,key_version=$6,key_rotation=$7 WHERE tenant_id=$1 AND checkpoint_ref=$2 AND envelope_key_ref=$3 AND state='committed'`, [input.tenantId, input.checkpointRef, input.currentKeyRef, nextObject, input.nextKeyRef, encrypted.keyVersion, rotation]); if (updated.rowCount !== 1) throw new Error('CHECKPOINT_KEY_ROTATION_CONFLICT'); }); await this.objectStore.delete({ tenantId: input.tenantId, objectRef: row.body_object_ref }); } finally { encrypted.ciphertext.fill(0); } } finally { plain.plaintext.fill(0); } }
  async tombstoneCheckpoint(input: { readonly tenantId: string; readonly checkpointRef: string; readonly now: string; readonly backupExpiresAt: string }): Promise<'tombstoned' | 'held' | 'conflict'> { return this.#tx(input.tenantId, 'principal://checkpoint-retention', async client => { const row = (await client.query<CheckpointRow>('SELECT * FROM agent_checkpoint_commit_operations WHERE tenant_id=$1 AND checkpoint_ref=$2 FOR UPDATE', [input.tenantId, input.checkpointRef])).rows[0]; if (!row) return 'conflict'; if (row.legal_hold) return 'held'; if (row.state === 'tombstoned' || row.state === 'backup_expired') return 'tombstoned'; if (row.state !== 'committed' || Date.parse(input.backupExpiresAt) <= Date.parse(input.now)) return 'conflict'; await client.query(`UPDATE agent_checkpoint_commit_operations SET state='tombstoned',tombstoned_at=$3,backup_expires_at=$4 WHERE tenant_id=$1 AND checkpoint_ref=$2`, [input.tenantId, input.checkpointRef, input.now, input.backupExpiresAt]); if (row.body_object_ref) await this.objectStore.delete({ tenantId: input.tenantId, objectRef: row.body_object_ref }); return 'tombstoned'; }); }
  async expireCheckpointBackup(input: { readonly tenantId: string; readonly checkpointRef: string; readonly now: string }): Promise<'deleted' | 'pending' | 'held'> { return this.#tx(input.tenantId, 'principal://checkpoint-retention', async client => { const row = (await client.query<CheckpointRow>('SELECT * FROM agent_checkpoint_commit_operations WHERE tenant_id=$1 AND checkpoint_ref=$2 FOR UPDATE', [input.tenantId, input.checkpointRef])).rows[0]; if (!row || row.state === 'backup_expired') return 'deleted'; if (row.legal_hold) return 'held'; if (row.state !== 'tombstoned' || !row.backup_expires_at || (row.backup_expires_at instanceof Date ? row.backup_expires_at.getTime() : Date.parse(row.backup_expires_at)) > Date.parse(input.now)) return 'pending'; await client.query(`UPDATE agent_checkpoint_commit_operations SET state='backup_expired',temporary_body_ref='tombstone://expired',body_object_ref=NULL,envelope_key_ref='kms://destroyed',key_version='destroyed' WHERE tenant_id=$1 AND checkpoint_ref=$2`, [input.tenantId, input.checkpointRef]); return 'deleted'; }); }
  async health(): Promise<AdapterHealth> { const [object, kms] = await Promise.all([this.objectStore.health(), this.kms.health()]); try { await this.#pool.query('SELECT 1'); return { healthy: object.healthy && kms.healthy, checkedAt: new Date().toISOString(), ...(!object.healthy || !kms.healthy ? { detail: 'CHECKPOINT_DEPENDENCY_UNAVAILABLE' } : {}) }; } catch { return { healthy: false, checkedAt: new Date().toISOString(), detail: 'CHECKPOINT_POSTGRES_UNAVAILABLE' }; } }
}
