import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { Pool } from 'pg';
import { sha256Digest, type UsageReceiptV1 } from '@sage/agent-contracts';
import { PostgresAgentStateAdapter, PostgresCheckpointLifecycleStore, PostgresConsumptionLedger } from './index.js';
const url = process.env.PHASE4_POSTGRES_URL;
const bodyDigest = (body: Uint8Array) => `sha256:${createHash('sha256').update(body).digest('hex')}`;
describe.skipIf(!url)('PostgreSQL production Checkpoint lifecycle', () => {
  it('atomically commits, validates full lineage resume, rotates keys, honors hold, and deletes after backup window', async () => {
    const migration = new PostgresAgentStateAdapter({ connectionString: url! }); await migration.migrate(); const tenantId = `checkpoint-${Date.now()}`; const pool = new Pool({ connectionString: url! }); await pool.query(`INSERT INTO agent_usage_accounts(tenant_id,account_ref,balance) VALUES($1,'acct',$2)`, [tenantId, { tokens: 100 }]); await pool.end();
    const ledger = new PostgresConsumptionLedger({ connectionString: url! }); const reservation = await ledger.reserve({ schemaVersion: '1', tenantId, accountRef: 'acct', invocationId: 'inv', ownerRef: 'principal://worker', taskId: 'task', runId: 'run', attemptId: 'attempt', specRef: 'spec://1', upperBound: { tokens: 10 }, leaseExpiresAt: new Date(Date.now() + 60_000).toISOString() }); const receiptBase: Omit<UsageReceiptV1, 'receiptDigest'> = { schemaVersion: '1', receiptRef: 'usage-receipt://checkpoint', tenantId, accountRef: 'acct', invocationId: 'inv', reservationRef: reservation.reservationRef, actual: { tokens: 1 }, cost: 0, committedAt: new Date().toISOString() }; const receipt = { ...receiptBase, receiptDigest: sha256Digest(receiptBase) }; expect((await ledger.commit({ reservation, receipt })).status).toBe('committed');
    const values = new Map<string, Uint8Array>(); const objects = { putTemporary: async ({ tenantId, operationId, ciphertext }: { tenantId: string; operationId: string; ciphertext: Uint8Array }) => { const temporaryRef = `temp://${tenantId}/${operationId}`; values.set(temporaryRef, new Uint8Array(ciphertext)); return { temporaryRef, etag: 'e' }; }, promote: async ({ temporaryRef, committedRef }: { temporaryRef: string; committedRef: string }) => { const value = values.get(temporaryRef); if (!value) throw new Error('missing'); values.set(committedRef, new Uint8Array(value)); return { status: 'promoted' as const, etag: 'e' }; }, get: async ({ committedRef }: { committedRef: string }) => { const value = values.get(committedRef); return value && new Uint8Array(value); }, delete: async ({ objectRef }: { objectRef: string }) => { values.delete(objectRef); }, health: async () => ({ healthy: true, checkedAt: new Date().toISOString() }) }; const kms = { encrypt: async ({ plaintext, keyRef }: { plaintext: Uint8Array; keyRef: string }) => ({ ciphertext: new Uint8Array(plaintext), keyVersion: keyRef }), decrypt: async ({ ciphertext, keyRef }: { ciphertext: Uint8Array; keyRef: string }) => ({ plaintext: new Uint8Array(ciphertext), keyVersion: keyRef }), health: async () => ({ healthy: true, checkedAt: new Date().toISOString() }) }; const store = new PostgresCheckpointLifecycleStore({ connectionString: url! }, objects, kms); const body = new TextEncoder().encode('checkpoint-body'); const descriptor = { tenantId, operationId: 'checkpoint-op', taskId: 'task', runId: 'run', attemptId: 'attempt', specDigest: `sha256:${'a'.repeat(64)}`, sequence: 1, stateSchema: 'AgentState.v1', engineCodec: 'reference@1', runtimeContractMajor: 1, effectReceiptRefs: [], usageReceiptRefs: [receipt.receiptRef], bodyDigest: bodyDigest(body), keyRef: 'kms://key-1', retentionClass: 'short' };
    const staged = await store.stageCheckpoint({ ...descriptor, body }); expect(staged).not.toHaveProperty('checkpointRef'); const committed = await store.finalizeCheckpoint({ tenantId, operationId: descriptor.operationId, fenceEpoch: staged.fenceEpoch }); expect(committed.state).toBe('committed'); if (committed.state !== 'committed') throw new Error('expected committed');
    const resume = { tenantId, checkpointRef: committed.checkpointRef!, taskId: descriptor.taskId, runId: descriptor.runId, attemptId: descriptor.attemptId, specDigest: descriptor.specDigest, sequence: 1, stateSchema: descriptor.stateSchema, engineCodec: descriptor.engineCodec, runtimeContractMajor: 1, effectReceiptRefs: [], usageReceiptRefs: [receipt.receiptRef], expectedBodyDigest: descriptor.bodyDigest, now: new Date().toISOString() }; await expect(store.resumeCheckpoint(resume)).resolves.toEqual(body); await expect(store.resumeCheckpoint({ ...resume, usageReceiptRefs: [] })).resolves.toBeUndefined(); await expect(store.resumeCheckpoint({ ...resume, tenantId: 'foreign' })).resolves.toBeUndefined();
    await store.rotateCheckpointKey({ tenantId, checkpointRef: committed.checkpointRef!, currentKeyRef: 'kms://key-1', nextKeyRef: 'kms://key-2' }); await expect(store.resumeCheckpoint(resume)).resolves.toEqual(body);
    await store.setCheckpointLegalHold({ tenantId, checkpointRef: committed.checkpointRef!, active: true, actorRef: 'principal://data-owner' }); expect(await store.tombstoneCheckpoint({ tenantId, checkpointRef: committed.checkpointRef!, now: new Date().toISOString(), backupExpiresAt: new Date(Date.now() + 1000).toISOString() })).toBe('held'); await store.setCheckpointLegalHold({ tenantId, checkpointRef: committed.checkpointRef!, active: false, actorRef: 'principal://data-owner' }); const deletionAt = new Date(Date.now() + 1000); expect(await store.tombstoneCheckpoint({ tenantId, checkpointRef: committed.checkpointRef!, now: new Date().toISOString(), backupExpiresAt: deletionAt.toISOString() })).toBe('tombstoned'); expect(await store.expireCheckpointBackup({ tenantId, checkpointRef: committed.checkpointRef!, now: new Date(deletionAt.getTime() - 1).toISOString() })).toBe('pending'); expect(await store.expireCheckpointBackup({ tenantId, checkpointRef: committed.checkpointRef!, now: deletionAt.toISOString() })).toBe('deleted'); await expect(store.resumeCheckpoint(resume)).resolves.toBeUndefined(); await migration.close();
  });
});
