import { Pool, type PoolClient, type PoolConfig, type QueryResultRow } from 'pg';
import type { CapabilityApproval, CapabilityGrant, KillSwitch } from '@sage/agent-contracts';
import { sha256Digest } from '@sage/agent-contracts';
import type { AdapterHealth, GovernanceSnapshotPort } from '@sage/platform-ports';

interface PayloadRow extends QueryResultRow { payload: unknown }
interface RevocationRow extends QueryResultRow { denied: boolean; revision: string | number; valid_until: Date | string }
export class PostgresGovernanceStore implements GovernanceSnapshotPort {
  readonly #pool: Pool; constructor(config: PoolConfig | Pool) { this.#pool = config instanceof Pool ? config : new Pool(config); }
  async #tenant<T>(tenantId: string, principalRef: string, work: (client: PoolClient) => Promise<T>): Promise<T> { const client = await this.#pool.connect(); try { await client.query('BEGIN'); await client.query('SELECT sage_security.set_request_context($1,$2)', [tenantId,principalRef]); const result = await work(client); await client.query('COMMIT'); return result; } catch (cause) { await client.query('ROLLBACK').catch(()=>undefined); throw cause; } finally { client.release(); } }
  async getGrant(input: { readonly tenantId: string; readonly grantRef: string }): Promise<CapabilityGrant | undefined> { return this.#tenant(input.tenantId,'principal://governance-reader',async client => (await client.query<PayloadRow>('SELECT grant_payload AS payload FROM agent_capability_grants WHERE tenant_id=$1 AND grant_ref=$2',[input.tenantId,input.grantRef])).rows[0]?.payload as CapabilityGrant|undefined); }
  async getApproval(input: { readonly tenantId: string; readonly approvalRef: string }): Promise<CapabilityApproval | undefined> { return this.#tenant(input.tenantId,'principal://governance-reader',async client => (await client.query<PayloadRow>('SELECT approval_payload AS payload FROM agent_capability_approvals WHERE tenant_id=$1 AND approval_ref=$2',[input.tenantId,input.approvalRef])).rows[0]?.payload as CapabilityApproval|undefined); }
  async listKills(input: { readonly tenantId: string; readonly scopeRefs: readonly string[] }): Promise<readonly KillSwitch[]> { return this.#tenant(input.tenantId,'principal://governance-reader',async client => (await client.query(`SELECT jsonb_strip_nulls(jsonb_build_object('schemaVersion','1','switchRef',switch_ref,'scopeKind',scope_kind,'scopeRef',scope_ref,'tenantId',CASE WHEN tenant_id='__global__' THEN NULL ELSE tenant_id END,'action',action,'active',active,'revision',revision,'reason',reason,'activatedBy',activated_by,'activatedAt',activated_at,'propagationDeadline',propagation_deadline)) AS payload FROM agent_kill_switches WHERE tenant_id IN ($1,'__global__') AND active AND scope_ref=ANY($2::text[])`,[input.tenantId,input.scopeRefs])).rows.map(row=>row.payload as KillSwitch)); }
  async revocationRevision(input: { readonly tenantId: string; readonly toolRef: string; readonly providerRef: string }): Promise<{ readonly denied: boolean; readonly revision: number; readonly validUntil: string }> { return this.#tenant(input.tenantId,'principal://governance-reader',async client => { const row=(await client.query<RevocationRow>(`SELECT EXISTS(SELECT 1 FROM agent_live_denies WHERE tenant_id=$1 AND active AND scope_ref IN ($2,$3) AND valid_until>clock_timestamp()) AS denied, COALESCE(MAX(revision),0) AS revision, COALESCE(MIN(valid_until),clock_timestamp()) AS valid_until FROM agent_live_denies WHERE tenant_id=$1`,[input.tenantId,input.toolRef,input.providerRef])).rows[0]!; return {denied:row.denied,revision:Number(row.revision),validUntil:new Date(row.valid_until).toISOString()}; }); }
  async putKill(input: KillSwitch): Promise<void> { await this.#tenant(input.tenantId??'__global__',input.activatedBy,async client=>{ await client.query(`INSERT INTO agent_kill_switches(tenant_id,switch_ref,scope_kind,scope_ref,action,active,revision,reason,activated_by,activated_at,propagation_deadline) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(tenant_id,switch_ref) DO UPDATE SET active=EXCLUDED.active,revision=EXCLUDED.revision,reason=EXCLUDED.reason,activated_by=EXCLUDED.activated_by,activated_at=EXCLUDED.activated_at,propagation_deadline=EXCLUDED.propagation_deadline WHERE agent_kill_switches.revision<EXCLUDED.revision`,[input.tenantId??'__global__',input.switchRef,input.scopeKind,input.scopeRef,input.action,input.active,input.revision,input.reason,input.activatedBy,input.activatedAt,input.propagationDeadline]); await client.query(`INSERT INTO agent_security_audit(tenant_id,category,decision,reason_code,actor_ref,correlation,authority_digest,occurred_at) VALUES($1,'kill',$2,'KILL_SWITCH_CHANGED',$3,$4,$5,$6)`,[input.tenantId??'__global__',input.active?'ACTIVATED':'DEACTIVATED',input.activatedBy,{switch_ref:input.switchRef,scope_ref:input.scopeRef,revision:input.revision},sha256Digest(input),input.activatedAt]); }); }
  async health(): Promise<AdapterHealth> { try { await this.#pool.query('SELECT 1'); return {healthy:true,checkedAt:new Date().toISOString()}; } catch { return {healthy:false,checkedAt:new Date().toISOString(),detail:'GOVERNANCE_STORE_UNAVAILABLE'}; } }
  async close(): Promise<void> { await this.#pool.end(); }
}
